var _arAdmShow=[],_arAdmNotShow=[],_arAdmCp=[],_chkPr=!1,_arNPr=[],_trackingSend=false, _arrBoxApp=[],_admDefault={},imgHost='http://admicro2.vcmedia.vn/adt/cpc/',admImgHost=false;

window.ADS_CHECKER={RAND:Math.random(),getPath2Check:function(a){var c=document.URL,d=document.referrer;return("Site:Pageurl"==a?c.replace(/\?i=([0-9]+)&bz=([0-9]+)&z=([0-9]+)#([0-9_0-9]+)/g,""):d.replace(/\?i=([0-9]+)&bz=([0-9]+)&z=([0-9]+)#([0-9_0-9]+)/g,"")).toLowerCase()},plugin:new function(){var a,c,d,b,g,f=this;f.installed=!1;f.raw="";f.major=-1;f.minor=-1;f.revision=-1;f.revisionStr="";var l=[{name:"ShockwaveFlash.ShockwaveFlash.7",version:function(a){return u(a)}},{name:"ShockwaveFlash.ShockwaveFlash.6",
version:function(a){var b="6.0.r21";try{a.AllowScriptAccess="always",b=u(a)}catch(c){}return b}},{name:"ShockwaveFlash.ShockwaveFlash",version:function(a){return u(a)}}],u=function(a){var b=-1;try{b=a.GetVariable("$version")}catch(c){}return b};f.majorAtLeast=function(a){return f.major>=a};f.minorAtLeast=function(a){return f.minor>=a};f.revisionAtLeast=function(a){return f.revision>=a};f.versionAtLeast=function(a){var b=[f.major,f.minor,f.revision],c=Math.min(b.length,arguments.length);for(i=0;i<
c;i++)if(b[i]>=arguments[i]){if(!(i+1<c&&b[i]==arguments[i]))return!0}else return!1};if(navigator.plugins&&0<navigator.plugins.length){if((l=navigator.mimeTypes)&&l["application/x-shockwave-flash"]&&l["application/x-shockwave-flash"].enabledPlugin&&l["application/x-shockwave-flash"].enabledPlugin.description){var x=l["application/x-shockwave-flash"].enabledPlugin.description,E=x,l=E.split(/ +/),x=l[2].split(/\./),l=l[3];a=E;c=parseInt(x[0],10);d=parseInt(x[1],10);b=l;g=parseInt(l.replace(/[a-zA-Z]/g,
""),10)||f.revision;f.raw=a;f.major=c;f.minor=d;f.revisionStr=b;f.revision=g;f.installed=!0}}else if(-1==navigator.appVersion.indexOf("Mac")&&window.execScript){x=-1;for(E=0;E<l.length&&-1==x;E++){a=-1;try{a=new ActiveXObject(l[E].name)}catch(s){a={activeXError:!0}}a.activeXError||(f.installed=!0,x=l[E].version(a),-1!=x&&(a=x,b=a.split(","),c=parseInt(b[0].split(" ")[1],10),d=parseInt(b[1],10),g=parseInt(b[2],10),b=b[2],f.raw=a.replace("Shockwave Flash ",""),f.major=c,f.minor=d,f.revision=g,f.revisionStr=
b))}}},checker:function(a,c,d){c=this.getPath2Check(c);switch(d){case "==":return c==a;case "!=":return c!=a;case "=~":return ADS_CHECKER.stripos(c,a,0);case "!~":return!ADS_CHECKER.stripos(c,a,0);case "=x":return a=RegExp(a),a.test(c);case "!x":return a=RegExp(a),!a.test(c)}return!1},getWeight:function(a,c){a=a.toString();arrWeight=a.split(",");return 1<arrWeight.length?(""==c||"0"==c)&&0<parseInt(arrWeight[0])?parseInt(arrWeight[0]):"1"==c&&0<parseInt(arrWeight[1])?parseInt(arrWeight[1]):"2"==c&&
0<parseInt(arrWeight[2])?parseInt(arrWeight[2]):"3"==c&&0<parseInt(arrWeight[3])?parseInt(arrWeight[3]):0:0==parseInt(arrWeight[0])?1:parseInt(arrWeight[0])},getQuery:function(a){a=a.replace(/[\[]/,"\\[").replace(/[\]]/,"\\]");var c=RegExp("[\\?&]"+a+"=([^&#]*)"),c=c.exec(document.referrer);return null==c?(c=RegExp("[\\?&]"+a+"=([^&#]*)"),c=c.exec(document.URL),null==c?"":decodeURIComponent(c[1].replace(/\+/g," "))):decodeURIComponent(c[1].replace(/\+/g," "))},getElementTop:function(a){if(document.getElementById)var c=
document.getElementById(a);else document.all&&(c=document.all[a]);if(null!=c){yPos=c.offsetTop;for(tempEl=c.offsetParent;null!=tempEl;)yPos+=tempEl.offsetTop,tempEl=tempEl.offsetParent;return yPos}return 0},checker_checker:function(a,c){if(a){for(var d=a.length,b="",g="",f=0;f<d;f++)if(void 0==a[f].data){for(var l="",u=0;u<a[f].length;u++)g="or"==a[f][u].join?"||":"&&",l+=(0!=u?g:"")+ADS_CHECKER.checker(a[f][u].data,a[f][u].type,a[f][u].logic);b+=(0!=f?c:"")+"("+l+")"}else b+=(0!=f?c:"")+ADS_CHECKER.checker(a[f].data,
a[f].type,a[f].logic);return b}return!1},setStorage:function(a,c,d,b,g,f){"localStorage"in window&&null!==window.localStorage?(ADS_CHECKER.lcStorage.set_item(a,c,d),("__R"!=a||"__RC"!=a)&&ADS_CHECKER.setCookie(a,"",d,b,g,f)):ADS_CHECKER.setCookie(a,c,d,b,g,f)},getStorage:function(a){return"localStorage"in window&&null!==window.localStorage?"__R"==a||"__RC"==a?ADS_CHECKER.getCookie(a):ADS_CHECKER.lcStorage.get_item(a):ADS_CHECKER.getCookie(a)},lcStorage:{timestamp:"timestamp_",get_exprises:function(a,
c,d,b){c=a.indexOf(c,d);d=a.length-1;return-1!=c?(b=a.indexOf(b,c),-1==b&&(b=d),a.substring(c,b)):""},set_item:function(a,c,d){var b="",g=(new Date).getTime(),f=this.timestamp,g=0==d||""==d?g+864E5:g+6E4*d,b="_azs"==a?";":",";d=this.get_exprises(c,f,0,b);c=""==d?c+(f+g.toString()+b):c.replace(d,f+g.toString());localStorage.setItem(a,c)},get_item:function(a,c){var d=localStorage.getItem(a),b=(new Date).getTime(),g=this.timestamp;if(""==d||null==d)return"";endchar="_azs"==a?";":",";var f=this.get_exprises(d,
g,0,endchar),f=f.replace(g,"");if(""==f||isNaN(parseInt(f))||parseInt(f)<b)return"";"undefined"!=typeof c&&(d=d.replace(g+f+endchar,""));return d},remove_item:function(a){localStorage.removeItem(a)},flush:function(){localStorage.clear()}},rand:function(a,c){var d=arguments.length;if(0==d)a=0,c=2147483647;else if(1==d)throw Error("Error");return Math.floor(Math.random()*(c-a+1))+a},subCookie:function(a,c,d){c=a.indexOf(c,d);d=a.length-1;if(-1!=c){var b=a.indexOf(";",c);-1==b&&(b=d);return a.substring(c,
b)}return""},popup_setCookie:function(a,c,d,b,g,f){d=(new Date(+new Date+6E5)).toGMTString();a=[a+"="+escape(c)];for(var l in d={expires:d,path:b,domain:g})d[l]&&a.push(l+"="+d[l]);return f&&a.push("secure"),document.cookie=a.join(";"),!0},setCookie:function(a,c,d,b,g,f){(new Date).getTime();b=""==b?"/":b;d=0==d||""==d?(new Date(+new Date+864E5)).toGMTString():(new Date(+new Date+6E4*d)).toGMTString();a=[a+"="+escape(c)];for(var l in d={expires:d,path:b,domain:g})d[l]&&a.push(l+"="+d[l]);return f&&
a.push("secure"),document.cookie=a.join(";"),!0},getCookie:function(a){return 0<document.cookie.length&&(c_start=document.cookie.indexOf(a+"="),-1!=c_start)?(c_start=c_start+a.length+1,c_end=document.cookie.indexOf(";",c_start),-1==c_end&&(c_end=document.cookie.length),unescape(document.cookie.substring(c_start,c_end))):""},in_array:function(a,c,d){var b=!1,g;d=!!d;for(g in c)if(d&&c[g]===a||!d&&c[g]==a){b=!0;break}return b},in_array_position:function(a,c,d){var b=0;d=!!d;for(var g=0,f=c.length;g<
f;g++){if(d&&c[g]===a||!d&&c[g]==a)return g;b++}return-1},array_duplicate:function(a,c){var d=[];if(!(0==a.length||0==c.length))for(var b=0,g=a.length;b<g;b++)ADS_CHECKER.in_array(a[b],c)&&(d[d.length]=a[b]);return d},array_diff:function(a,c){for(var d=[],b=0,g=a.length;b<g;b++)ADS_CHECKER.in_array(a[b],c)||(d[d.length]=a[b]);return d},stripos:function(a,c,d){a=(a+"").toLowerCase();c=(c+"").toLowerCase();return-1!==a.indexOf(c,d)},processClick:function(a,c){for(var d=c.length,b=0;b<d;b++){var g=document.createElement("iframe");
g.width=0;g.height=0;g.style.border=0;g.src=c;document.getElementById(a).appendChild(g)}},randBanner:function(){return 0==Math.floor(100*Math.random())%2?0:1}};var ADS_Location=ADS_CHECKER.getStorage("__R"),ADS_City=ADS_CHECKER.getStorage("__RC"),ADS_Game=ADS_CHECKER.getStorage("g"),ADS_Gender=ADS_CHECKER.getStorage("s");ADS_CHECKER.flash=ADS_CHECKER.plugin.installed;ADS_Game=""==ADS_Game?0:parseInt(ADS_Game.toString().replace(/timestamp_([0-9]+)\,/g,""));
ADS_Gender=""==ADS_Gender?0:parseInt(ADS_Gender.toString().replace(/timestamp_([0-9]+)\,/g,""));
""!=ADS_Location&&(0<=parseInt(ADS_Location)&&3>=parseInt(ADS_Location)?(""==ADS_City||"undefined"==typeof ADS_City)&&ADS_CHECKER.setStorage("__RC",ADS_Location,"","/"):(4==parseInt(ADS_Location)||7<=parseInt(ADS_Location)&&31>parseInt(ADS_Location)?ADS_CHECKER.setStorage("__R","1","","/"):31<=parseInt(ADS_Location)||51>=parseInt(ADS_Location)?ADS_CHECKER.setStorage("__R","2","","/"):ADS_CHECKER.setStorage("__R","3","","/"),ADS_CHECKER.setStorage("__RC",ADS_Location,"","/")),"0"==ADS_Location&&"0"!=
ADS_City&&(4==parseInt(ADS_City)||7<=parseInt(ADS_City)&&31>parseInt(ADS_City)?(ADS_Location=1,ADS_CHECKER.setStorage("__R","1","","/")):31<=parseInt(ADS_City)&&51>=parseInt(ADS_City)?(ADS_Location=2,ADS_CHECKER.setStorage("__R","2","","/")):100>=parseInt(ADS_City)&&(ADS_Location=3,ADS_CHECKER.setStorage("__R","3","","/"))));
function banner(a){if(a){a={bid:parseInt(a.bid),title:a.title,type:a.type,link:a.link,src:a.src,alt:a.alt?a.alt:"",location:a.location,width:parseInt(a.width),height:parseInt(a.height),created:a.created?a.created:null,expired:a.expired?a.expired:null,slotIdx:a.slotIdx,attr:a.attr,terms:a.terms,clicks:a.clicks?a.clicks:null,views:a.views?a.views:null,cpname:a.cpname,counter:a.counter,iframe:a.iframe,sort:a.sort,cpm:a.cpm?a.cpm:0,link_clicks:a.link_clicks,link_views:a.link_views,weight:a.weight?a.weight:
0===a.weight?0:1,gr:a.gr?a.gr:0,pr:a.pr?a.pr:"",is_default:a.is_default?a.is_default:0,bannertype:a.bannertype?a.bannertype:0,ckPr:!1,bool:!1};for(var c in a)this[c]=a[c]}}
banner.prototype.logging=function(a,c,d,b){var g=this.link?this.link:"-1";c?(c="http://logging.admicro.vn/_adv.gif",g=b?encodeURIComponent(c+"?adm_domain="+escape(document.URL)+"&adm_campaign="+(this.cpname?this.cpname:"")+"&adm_aditem="+this.bid+"&adm_zoneid="+a+"&adm_channelid=-1&adm_random="+d):c+"?adm_domain="+escape(document.URL)+"&adm_campaign="+(this.cpname?this.cpname:"")+"&adm_aditem="+this.bid+"&adm_zoneid="+a+"&adm_channelid=-1&adm_random="+d):(c="http://logging.admicro.vn/_adc.html",g=
b?encodeURIComponent(c+"?adm_domain="+escape(document.URL)+"&adm_campaign="+(this.cpname?this.cpname:"")+"&adm_aditem="+this.bid+"&adm_zoneid="+a+"&adm_channelid=-1&adm_rehttp="+escape(g)+"&adm_random="+d):c+"?adm_domain="+escape(document.URL)+"&adm_campaign="+(this.cpname?this.cpname:"")+"&adm_aditem="+this.bid+"&adm_zoneid="+a+"&adm_channelid=-1&adm_rehttp="+encodeURIComponent(g)+"&adm_random="+d);return g};
banner.prototype.renderLinkViews=function(){var a="";if(null!=this.link_views){var c=this.link_views.length;if(document.images)for(var d=[],b=0;b<c;b++)d[b]=new Image,d[b].src=this.link_views[b];else a+='<div style="position:absolute;background:url('+this.link_views[b]+');height:0; width:0" ><span style="height:0; width:0"></span></div>'}return a};
banner.prototype.renderLinkClicks=function(a){var c="";if(null!=this.link_clicks){c="swf"==this.type?c+'onmousedown="':c+'onclick="';c+="ADS_CHECKER.processClick('"+a+"',[";a=this.link_clicks.length;for(var d=0;d<a;d++)c+="'"+this.link_clicks[d]+"'"+(d<a-1?",":"");c+=']);"'}return c};
banner.prototype.renderBanner=function(a,c,d,b,g){g='<div id="'+a+'" class="'+g+'" '+(b?'style="display:none"':"")+">";switch(this.type){case "gif":case "jpeg":case "png":g+=this.renderBannerImage(a,c,d,b);break;case "swf":g+=this.renderBannerFlash(a,c,d,b);break;case "html":a=""==ADS_Location||isNaN(parseInt(ADS_Location))||"0"==ADS_Location?1:parseInt(ADS_Location);b=this.src;var f=ADS_CHECKER.getQuery("z");parseInt(ADS_CHECKER.getQuery("bz"));var l=parseInt(ADS_CHECKER.getQuery("i"));""!=f&&""!=
l?(b=b.replace(/(ssvzone|pluszone)_([0-9]+).js/,"$1_$2_"+a+".js?random="+Math.random()),b=b.replace(/cpmzone_([0-9]+).js/,"cpmzone_$1.js?random="+Math.random())):b=b.replace(/(ssvzone|pluszone)_([0-9]+).js/,"$1_$2_"+a+".js");g+=(b+"").replace(/\0/g,"0").replace(/\\([\\'"])/g,"$1")}this.counter&&(document.images?(new Image).src=this.logging(c,!0,d):g+='<div style="background:url('+this.logging(c,!0,d)+'); height:0; width:0;position:absolute;border:none" ><span style="height:0; width:0"></span></div>');
return g+this.renderLinkViews()+"</div>"};banner.prototype.renderBannerImage=function(a,c,d){var b='<img border="0" id="'+a+'" src="'+(admImgHost?this.src.replace("admicro2.","admicro2-hcm."):this.src)+'"'+(this.width?' width="'+this.width+'"':"")+(this.height?' height="'+this.height+'"':"");if(this.attr)for(var g in this.attr)b+=" "+g+'="'+this.attr[g]+'"';b+=" "+this.renderLinkClicks(a)+" />";return this.link?'<a href="'+this.logging(c,!1,d)+'" target="_blank">'+b+"</a>":b};
banner.prototype.renderBannerFlash=function(a,c,d){var b="",g=this.link?"alink1="+this.logging(c,!1,d,!0)+"&amp;atar1=_blank":"",f=!1;if(this.attr)for(var l in this.attr)"flashvars"==l&&(this.attr[l]=g+"&amp;"+this.attr[l],f=!0),b+=" "+l+'="'+this.attr[l]+'"';""!=g&&!f&&(b+=' flashvars="'+g+'"');if(ADS_CHECKER.flash)return"<embed "+this.renderLinkClicks(a)+' src="'+(admImgHost?this.src.replace("admicro2.","admicro2-hcm."):this.src)+'" height="'+this.height+'" alt="'+this.alt+'" align="middle" width="'+
this.width+'" pluginspage="http://www.macromedia.com/go/getflashplayer" type="application/x-shockwave-flash" '+b+' allowscriptaccess="always" wmode="transparent" quality="high" />';if(null!=this.alt&""!=this.alt){b='<img border="0" id="'+a+'" src="'+(admImgHost?this.alt.replace("admicro2.","admicro2-hcm."):this.alt)+'"'+(this.width?' width="'+this.width+'"':"")+(this.height?' height="'+this.height+'"':"");if(this.attr)for(l in this.attr)b+=" "+l+'="'+this.attr[l]+'"';b+=" "+this.renderLinkClicks(a)+
" />";return this.link?'<a href="'+this.logging(c,!1,d)+'" target="_blank">'+b+"</a>":b}return"<embed "+this.renderLinkClicks(a)+' src="'+(admImgHost?this.src.replace("admicro2.","admicro2-hcm."):this.src)+'" height="'+this.height+'" alt="'+this.alt+'" align="middle" width="'+this.width+'" pluginspage="http://www.macromedia.com/go/getflashplayer" type="application/x-shockwave-flash" '+b+' allowscriptaccess="always" wmode="transparent" quality="high" />'};
banner.prototype.time=function(){return ads_time_server?ads_time_server:Math.round((new Date).getTime()/1E3)};banner.prototype.checkViews=function(a){a=a.substring(0,a.length-1);eval("view = view_"+a+this.bid);return!0};banner.prototype.checkClicks=function(a){a=a.substring(0,a.length-1);eval("click = click_"+a+this.bid);return!0};banner.prototype.checkExpired=function(){var a=this.time();return this.created<a&&null==this.expired||this.created<a&&a<this.expired?!1:!0};
banner.prototype.checkInvalid=function(a){return this.checkExpired()||!this.checkViews(a)||!this.checkClicks(a)?!1:!0};banner.prototype.checkPr=function(){var a=document.URL,c=this.pr.split("|");this.ckPr=!1;for(var d=0,b=c.length;d<b;d++)if(-1!=a.indexOf(c[d]))return _chkPr=this.ckPr=!0;return!1};
banner.prototype.process=function(){if(this.terms){for(var a=this.terms,c=a.length,d="",b="",g=0;g<c;g++)0!=g&&(b="or"==a[g].join?"||":"&&"),d=a[g].channel?d+(b+("!~"==a[g].logic?"!":"")+"("+ADS_CHECKER.checker_checker(a[g].data,"=="==a[g].logic?"&&":"||")+")"):d+(b+ADS_CHECKER.checker(a[g].data,a[g].type,a[g].logic));this.bool=eval(d)}else this.bool=!0;"undefined"!=typeof __arCPM4K&&(0!=__arCPM4K.length&&ADS_CHECKER.in_array(this.bid,__arCPM4K))&&(this.bool=!1);1===this.gr&&ADS_CHECKER.in_array(parseInt(this.cpname),
_arAdmNotShow)&&(this.bool=!1);""!=this.pr?this.bool=this.checkPr():_chkPr&&(this.bool=!1);!ADS_CHECKER.flash&&(""==this.alt&&"swf"==this.type)&&(this.bool=!1);var a=this.location,a="undefined"==a||null==a?0:a,a=","+(""==a?0:a)+",",c=","+ADS_Location+",",d=","+ADS_City+",",b=this.weight,g=[],b=b.toString(),g=b.split(","),f=/,[1|2|3],[1|2|3],[1|2|3],/g;if((this.bool=this.bool&&(",,"==a||f.test(a)||",0,"==a||-1!=a.toString().indexOf(d)||-1!=a.toString().indexOf(c)?!0:!1))&&1<g.length&&!(0<parseInt(g[0])||
0<parseInt(g[1])&&",1,"==c||0<parseInt(g[2])&&",2,"==c||0<parseInt(g[2])&&",3,"==c))this.bool=this.bool&&!1;if(this.bool&&6==this.bannertype&&(0==ADS_CHECKER.getWeight(b,ADS_Location)||1==ADS_CHECKER.getWeight(b,ADS_Location)))1<=_arrBoxApp.length&&(this.bool=!1),_arrBoxApp.push(this.bid);9==this.bannertype&&1100>parseInt(screen.width)&&(this.bool=!1)};
function zone(a,c,d,b,g){"undefined"==typeof _admDefault[a]&&(_admDefault[a]={});_admDefault[a].effect=c.effect;_admDefault[a].rotate=c.slots_rotate;a={banners:[],zoneid:a?a:-1,width:d,height:b,attr:g,style:c,share:c.share?c.share:3,slots:null,time:1E4,preload_time:3E3,rand_num:ADS_CHECKER.RAND,theme:[],run_fix:!1,cpm:null,cpd:null,ie:"Opera"==navigator.appName||"Microsoft Internet Explorer"==navigator.appName};for(var f in a)this[f]=a[f]}zone.prototype.removeHidden=function(){};
zone.prototype.removeHtml=function(a){for(var c=1;c<=this.style.slot;c++){var d=a.indexOf("slot"+c+"_content"),b=a.lastIndexOf("<div",d),g=a.indexOf("</div>",d);0<=d&&(d=a.substring(b,g+6),a=a.replace(d,""))}return a};zone.prototype.mkRandCPM=function(a){var c=0,d;for(d in a)c+=parseInt(a[d]);var b=[],g=0;for(d in a)b.push((0<g?b[g-1]:0)+Math.floor(1E3*parseInt(a[d])/c)/1E3),g++;a=b.length;0<a&&(b[a-1]=1);return b};
zone.prototype.choseRandom=function(a){for(var c=Math.random(),d=0;d<a.length;d++)if(c<=a[d])return d;return 0};
zone.prototype.getBannerRun=function(a){var c=parseInt(ADS_CHECKER.getQuery("z")),d=parseInt(ADS_CHECKER.getQuery("bz")),b=parseInt(ADS_CHECKER.getQuery("z1")),g=parseInt(ADS_CHECKER.getQuery("bz1"));ADS_CHECKER.getStorage("_azs");var f=this.zoneid,l=this.style.slot,u=this.style.sort_banner_slot,x=!1,E=[],s=[],t=[],B=[],w=[],E=[],q=[],e=[],r=0,p={},h=!1,A=[],F=[],j=[],z=[],n=[];this.spamCpd=[];this.spamBidCpd=[];this.spamlstCp=[];this.bz=0;for(var b=isNaN(b)?0:b,g=isNaN(g)?0:g,c=isNaN(c)?0:c,d=isNaN(d)?
0:d,k=0;k<this.style.slot;k++){q[k]=[];e[k]=[];_admDefault[f][k]=[];t[k]=0;if(0!=u[k+1])for(var m=0;m<u[k+1].length;m++)q[k][m]=[],e[k][m]=[],_admDefault[f][k][m]=[];E[k]=[];s[k]=k+1;t[k]=0}ADS_City=""==ADS_City?0:ADS_City;var y=[],C=[],G=[];if("101"==ADS_City)for(var K in a)m=new banner(a[K]),m.process(),!0==m.bool&&0!=m.is_default&&(m.bool=!1),!_chkPr&&(m.bool&&-1!=m.location.indexOf(ADS_City))&&(y.push(m.bid),G.push({bid:m.bid,slotIdx:m.slotIdx,sort:m.sort,cpm:m.cpm}),C.push(m.slotIdx));for(K in a)if(m=
new banner(a[K]),"undefined"!=typeof a[K].bid){var D=parseInt(a[K].bid.toString()),H=a[K].slotIdx,I=ADS_CHECKER.getWeight(a[K].weight,ADS_Location);if(1==I||0==I)B.push(D);else if(d==D)B.push(D);else for(k=0;k<I;k++)B.push(D+"_"+k);m.process();if(!0==m.bool&&(0!=m.is_default||-1!=m.src.indexOf("ssvzone_")))0!=m.is_default&&(m.bool=!1),0===u[m.slotIdx]?_admDefault[f][m.slotIdx-1].push(m):u[m.slotIdx].length>=m.sort&&0<m.sort&&_admDefault[f][m.slotIdx-1][m.sort-1].push(m);m.ckPr&&n.push(m.bid);x=!1;
if(m.bool||m.bool&&(D==d&&f==c||D==g&&f==b)){1===m.gr&&(F.push(m.bid),ADS_CHECKER.in_array(parseInt(m.cpname),z)||z.push(parseInt(m.cpname)),j.push({bid:m.bid,cid:parseInt(m.cpname),Idx:m.slotIdx,sort:m.sort}));var L=!1;if(0===I){var J=ADS_CHECKER.getStorage("_popup"),M="w"+m.bid.toString()+":",N=Math.floor((new Date).getTime()/1E3);if(""==J)L=!0,J=M+N.toString()+";";else{var O=ADS_CHECKER.subCookie(J,M,0);""==O?(L=!0,J+=M+N.toString()+";"):600<=N-parseInt(O.replace(M,""))&&(L=!0,J=J.replace(O+";",
M+N.toString()+";"))}L&&ADS_CHECKER.setStorage("_popup",J,10,"/")}x=x?x:D==d&&f==c||D==g&&f==b;r=D==d&&f==c||D==g&&f==b?H:r;this.bz=x?D:this.bz;!1===x&&(!0===L&&f!=c)&&(x=!0,r=H,this.bz=D);w.push(D);1<=parseInt(H)&&E[H-1].push(D);if(1==m.cpm)if(0<m.sort&&0!=u[H])if(1===I||0===I)q[H-1][m.sort-1].push(D);else if(this.bz==D)q[H-1][m.sort-1].push(D);else for(k=0;k<I;k++)q[H-1][m.sort-1].push(D+"_"+k);else{if(0==m.sort)if(1===I||0===I)q[H-1].push(D);else if(this.bz==D)q[H-1].push(D);else for(k=0;k<I;k++)q[H-
1].push(D+"_"+k)}else if(8==m.bannertype&&(h||(h=!0),p[m.bid]={bid:m.bid,slotIdx:m.slotIdx,sort:m.sort,weight:m.weight},ADS_CHECKER.in_array(m.slotIdx,A)||A.push(m.slotIdx)),0<m.sort&&0!=u[H])if(1===I||0===I)e[H-1][m.sort-1].push(D);else if(this.bz==D)e[H-1][m.sort-1].push(D);else for(k=0;k<I;k++)e[H-1][m.sort-1].push(D+"_"+k);else if(0==m.sort)if(1===I||0===I)e[H-1].push(D);else if(this.bz==D)e[H-1].push(D);else for(k=0;k<I;k++)e[H-1].push(D+"_"+k)}}if(0<n.length){if(0<_arNPr.length){k=0;for(c=_arNPr.length;k<
c;k++)w=document.getElementById("ads_zone"+_arNPr[k]),"undefined"!=typeof w&&null!=typeof w&&(w.style.display="none")}for(var v=this.style.sort_banner_slot,w=n,k=0;k<l;k++)if(0==v[k+1])0<e[k].length&&(e[k]=ADS_CHECKER.array_duplicate(n,e[k])),0<q[k].length&&(q[k]=ADS_CHECKER.array_duplicate(n,q[k]));else{m=0;for(d=v[k+1].length;m<d;m++)0<e[k][m].length&&(e[k][m]=ADS_CHECKER.array_duplicate(n,e[k][m])),0<q[k][m].length&&(q[k][m]=ADS_CHECKER.array_duplicate(n,q[k][m]))}}else if(!_chkPr&&(_arNPr.push(f),
0<y.length))if(n=this.style.slots_rotate,null!=n){m=0;for(c=C.length;m<c;m++)if(0==u[C[m]])e[C[m]-1]=ADS_CHECKER.array_duplicate(y,e[C[m]-1]),q[C[m]-1]=ADS_CHECKER.array_duplicate(y,q[C[m]-1]);else for(v in G)ADS_CHECKER.in_array(G[v].slotIdx,[C[m]])&&(q[C[m]-1][G[v].sort-1]=ADS_CHECKER.array_duplicate(y,q[C[m]-1][G[v].sort-1]),e[C[m]-1][G[v].sort-1]=ADS_CHECKER.array_duplicate(y,e[C[m]-1][G[v].sort-1]));k=0;for(c=n.length;k<c;k++)if(b=ADS_CHECKER.array_duplicate(C,n[k]),0<b.length){m=0;for(d=n[k].length;m<
d;m++)if(ADS_CHECKER.in_array(n[k][m],b))if(0==u[n[k][m]])e[n[k][m]-1]=ADS_CHECKER.array_duplicate(y,e[n[k][m]-1]),q[n[k][m]-1]=ADS_CHECKER.array_duplicate(y,q[n[k][m]-1]);else for(v in G)ADS_CHECKER.in_array(G[v].slotIdx,b)&&(q[n[k][m]-1][G[v].sort-1]=ADS_CHECKER.array_duplicate(y,q[n[k][m]-1][G[v].sort-1]),e[n[k][m]-1][G[v].sort-1]=ADS_CHECKER.array_duplicate(y,e[n[k][m]-1][G[v].sort-1]));else if(0==u[n[k][m]])e[n[k][m]-1]=[],q[n[k][m]-1]=[];else{v=0;for(l=u[n[k][m]].length;v<l;v++)q[n[k][m]-1][u[n[k][m]][v]-
1]=[],e[n[k][m]-1][u[n[k][m]][v]-1]=[]}}}else for(k=1;k<=l;k++)if(ADS_CHECKER.in_array(k,C))if(0==u[k])e[k-1]=ADS_CHECKER.array_duplicate(y,e[k-1]),q[k-1]=ADS_CHECKER.array_duplicate(y,q[k-1]);else for(v in G)G[v].slotIdx==k&&(q[k-1][G[v].sort-1]=ADS_CHECKER.array_duplicate(y,q[k-1][G[v].sort-1]),e[k-1][G[v].sort-1]=ADS_CHECKER.array_duplicate(y,e[k-1][G[v].sort-1]));this.spamCpd=F;this.spamBidCpd=j;this.spamlstCp=z;j=[];z=0;if(!x&&h&&0==F.length&&!_chkPr){h=this.style.slots_rotate;x=this.style.effect;
for(k in p)if(j.push(p[k].bid),2==x[p[k].slotIdx]&&(l=u[p[k].slotIdx],C=y=0,F=p[k].slotIdx,m=p[k].sort,0==q[F-1][m-1].length)){v=0;for(c=l.length;v<c;v++)l[v]==p[k].sort?C=e[F-1][m-1].length:y=Math.max(y,e[F-1][l[v]-1].length);if(C<y){c=y-C;for(v=0;v<c;v++)l=1!=c?"0_"+v:0,e[F-1][m-1].push(l),ADS_CHECKER.in_array(0,w)||w.push(0),ADS_CHECKER.in_array(l,B)||(z++,B.push(l),j.push(l))}}F=s;if(null!=h){k=0;for(c=h.length;k<c;k++)if(v=ADS_CHECKER.array_duplicate(h[k],A),F=ADS_CHECKER.array_diff(F,h[k]),
0<v.length){y=!1;m=0;for(d=h[k].length;m<d;m++)if(2==x[h[k][m]]){v=0;for(l=u[h[k][m]].length;v<l;v++)if(0<q[h[k][m]-1][v].length){y=!0;break}}else if(0<q[h[k][m]-1].length){y=!0;break}if(!y){m=C=0;for(d=h[k].length;m<d;m++)if(2==x[h[k][m]]){v=y=0;for(l=u[h[k][m]].length;v<l;v++)y=Math.max(y,e[h[k][m]-1][v].length);C+=y}else C+=e[h[k][m]-1].length;m=this.share-C;y=ADS_CHECKER.array_duplicate(h[k],A);if(0<y.length){C=Math.floor(Math.random()*y.length);for(v=0;v<m;v++){if(2==x[y[C]]){d=G=n=0;for(l=u[y[C]].length;d<
l;d++)b=e[y[C]-1][d].length,n=Math.max(n,b),n==b&&(G=d);l="0_"+z;e[y[C]-1][G].push(l)}else l="0_"+z,e[y[C]-1].push(l);ADS_CHECKER.in_array(0,w)||w.push(0);ADS_CHECKER.in_array(l,B)||(z++,B.push(l),j.push(l))}}}}}for(k in p)if(ADS_CHECKER.in_array(p[k].slotIdx,F))if(2==x[p[k].slotIdx]){if(0==q[p[k].slotIdx-1][p[k].sort-1].length){A=this.share-e[p[k].slotIdx-1][p[k].sort-1].length;for(v=0;v<A;v++)l="0_"+z,e[p[k].slotIdx-1][p[k].sort-1].push(l),ADS_CHECKER.in_array(0,w)||w.push(0),ADS_CHECKER.in_array(l,
B)||(z++,B.push(l),j.push(l))}}else if(0==q[p[k].slotIdx-1].length){A=this.share-e[p[k].slotIdx-1].length;for(v=0;v<A;v++)l="0_"+z,e[p[k].slotIdx-1].push(l),ADS_CHECKER.in_array(0,w)||w.push(0),ADS_CHECKER.in_array(l,B)||(z++,B.push(l),j.push(l))}}if(0==w.length)this.drawEmpty();else{this.abr=w;this.cpm=q;this.cpd=e;this.arrb=B;this.trk=0!=r?!0:!1;this.trks=r;this.arrSlot=s;this.arr7k=j;if(0<e.length){k=0;for(c=e.length;k<c;k++)if(0==u[k+1])t[k]=e[k].length;else{m=0;for(d=u[k+1].length;m<d;m++)t[k]=
Math.max(t[k],e[k][m].length)}this.slotSize=t}this.drawBannerRun(a)}};zone.prototype.resetParam=function(){1!=ADS_CHECKER.getQuery("admdebug")&&(this.style=this.arrSlot=this.cookie=this.html=null)};zone.prototype.renderIframe=function(a,c,d,b){return'<iframe src="" style="border:none;" width="'+d+'" height="'+b+'" marginheight="0" align="top" scrolling="No" frameborder="0" hspace="0" vspace="0" class="'+c+'" id="'+a+'"><html><head><style>body{margin:0;}</style></head><body></body></html></iframe>'};
zone.prototype.fillterCpdShow=function(a,c){var d=this.style.effect,b=this.spamBidCpd,g=this.cpd;ADS_CHECKER.in_array(a.bid,this.spamCpd)&&(ADS_CHECKER.in_array(parseInt(a.cpname),_arAdmShow)||_arAdmShow.push(parseInt(a.cpname)));if(2===d[a.slotIdx])for(var f=0,l=b.length;f<l;f++){b[f].Idx==a.slotIdx&&(b[f].cid==parseInt(a.cpname)&&b[f].sort>a.sort)&&(this.cpd[a.slotIdx-1][b[f].sort-1]=[b[f].bid]);if(0===a.gr&&a.slotIdx==b[f].Idx&&a.sort==b[f].sort||0===a.gr&&a.slotIdx!=b[f].Idx||1===a.gr&&a.slotIdx==
b[f].Idx&&a.sort==b[f].sort&&parseInt(a.cpname)!=b[f].cid||parseInt(a.cpname)!=b[f].cid&&b[f].Idx!=a.slotIdx&&0<c.length&&ADS_CHECKER.in_array(b[f].Idx,c))ADS_CHECKER.in_array(b[f].cid,_arAdmNotShow)||_arAdmNotShow.push(b[f].cid);if(a.slotIdx==b[f].Idx&&b[f].sort==a.sort||a.slotIdx==b[f].Idx&&ADS_CHECKER.in_array(b[f].cid,_arAdmNotShow))this.cpd[a.slotIdx-1][b[f].sort-1]=ADS_CHECKER.array_diff(g[a.slotIdx-1][b[f].sort-1],[b[f].bid])}else{f=0;for(l=b.length;f<l;f++)if(b[f].Idx==a.slotIdx&&a.bid!=b[f].bid&&
!ADS_CHECKER.in_array(b[f].cid,_arAdmShow)||0<c.length&&b[f].Idx!=a.slotIdx&&ADS_CHECKER.in_array(b[f].Idx,c)&&!ADS_CHECKER.in_array(b[f].cid,_arAdmShow))ADS_CHECKER.in_array(b[f].cid,_arAdmNotShow)||_arAdmNotShow.push(b[f].cid)}f=0;for(l=b.length;f<l;f++)ADS_CHECKER.in_array(b[f].cid,_arAdmNotShow)&&(2==d[b[f].Idx]?this.cpd[b[f].Idx-1][b[f].sort-1]=ADS_CHECKER.array_diff(this.cpd[b[f].Idx-1][b[f].sort-1],[b[f].bid]):this.cpd[b[f].Idx-1]=ADS_CHECKER.array_diff(this.cpd[b[f].Idx-1],[b[f].bid]))};
zone.prototype.drawBannerRun=function(a){var c=this.style.html,d=ADS_CHECKER.getStorage("_azs"),b=this.subCookie(d,"Ver:",0),g=this.style.slots_rotate,f=this.style.effect,l=this.arrSlot,u=this.style.sort_banner_slot,x=this.style.banner_default,E=this.share,s=this.zoneid,t=this.arrb,B=[];""==b&&(d="Ver:19;");this.cookie=d;var w=[];if(this.trk){if(0==u[this.trks])this.cpd[this.trks-1]=[this.bz];else for(var q=0,e=this.cpd[this.trks-1].length;q<e;q++)if(-1!=this.cpd[this.trks-1][q].indexOf(this.bz)||
-1!=this.cpm[this.trks-1][q].indexOf(this.bz)){this.cpd[this.trks-1][q]=[this.bz];break}if(g)for(var b=0,r=g.length;b<r;b++)l=ADS_CHECKER.array_diff(l,g[b]),-1!=g[b].indexOf(this.trks)?w.push(this.trks.toString()):(q=this.getSlotRun(s,b,g[b],d),d=this.cookie,q&&w.push(q.toString()))}else if(g){b=0;for(r=g.length;b<r;b++){l=ADS_CHECKER.array_diff(l,g[b]);if(q=this.getSlotRun(s,b,g[b],d))for(var d=ADS_CHECKER.array_diff(g[b],[parseInt(q.replace(/_[0-9]+/g,""))]),p=this.spamBidCpd.length,h=0;h<p;h++)ADS_CHECKER.in_array(this.spamBidCpd[h].Idx,
d)&&(ADS_CHECKER.in_array(this.spamBidCpd[h].cid,_arAdmNotShow)||_arAdmNotShow.push(this.spamBidCpd[h].cid));d=this.cookie;q&&w.push(q.toString())}}for(var q=this.cpd,A=this.cpm,b=0;b<w.length;b++){var p=w[b].split("_"),F="";if(-1!=w[b].indexOf("m")){e=[];for(h=0;h<g[b].length;h++)if(2==f[g[b][h]]){for(var j=r=0;j<this.cpm[g[b][h]-1].length;j++)0<this.cpm[g[b][h]-1][j].length&&(r=Math.max(r,this.cpm[g[b][h]-1][j].length));if(0!=r)for(j=0;j<r;j++)e.push(g[b][h]+"_"+j)}else if(0<this.cpm[g[b][h]-1].length)for(j=
0;j<this.cpm[g[b][h]-1].length;j++)e.push(g[b][h]+"_"+j);h="z"+s+"m"+b+":";r=this.subCookie(d,h,0);if(""==r)0<e.length&&(j=ADS_CHECKER.rand(0,e.length-1),p[0]=e[j].replace(/_([0-9]+)/,""),d+=h+e[j]+";");else if(j=r.replace(h,"").split(","),0<ADS_CHECKER.array_diff(j,e).length&&0<e.length)j=ADS_CHECKER.rand(0,e.length-1),p[0]=e[j].replace(/_([0-9]+)/,""),d=d.replace(r+";",h+e[j]+";");else{var z=ADS_CHECKER.array_diff(e,j);0==z.length?1==e.length?p[0]=e[0].replace(/_([0-9]+)/,""):(h=this.strReverse(r.replace(h,
"")),1<h.split(",").length&&(p[0]=h.split(",")[0].replace(/_([0-9]+)/,""),d=d.replace(r+";","z"+s+"m"+b+":"+h+";"))):(j=ADS_CHECKER.rand(0,z.length-1),p[0]=z[j].replace(/_([0-9]+)/,""),d=d.replace(r+";",r+","+z[j]+";"))}}this.cookie=d;if(2==f[p[0]]){for(var n=r=0;n<u[p[0]].length;n++)r=Math.max(r,this.cpd[p[0]-1][n].length);for(n=0;n<u[p[0]].length;n++){z=[];j=[];for(h=0;h<q[p[0]-1][n].length;h++)z.push(ADS_CHECKER.in_array_position(q[p[0]-1][n][h],t));for(h=0;h<A[p[0]-1][n].length;h++)j.push(ADS_CHECKER.in_array_position(A[p[0]-
1][n][h],t));if(0<j.length&&z.length<r){h=0;for(e=z.length;h<r-e;h++)z.push("m"+(1<r-e?"_"+h:""))}h="z"+s+"s"+p[0]+"_"+n+":";this.subCookie(d,h,0);h=!1;h=-1!=w[b].indexOf("m")?this.getMix(j,d,"z"+s+"sm"+p[0]+"_"+n+":"):this.getMix(z,d,"z"+s+"s"+p[0]+"_"+n+":");d=this.cookie;e="";!1===h||-1!=h.toString().indexOf("m")?0<j.length?(h=this.getMix(j,d,"z"+s+"sm"+p[0]+"_"+n+":"),d=this.cookie,e=0,e="string"==typeof t[h]?parseInt(t[h].replace(/_[0-9]/g,"")):t[h],j=new banner(a[e]),0<this.spamlstCp.length&&
0<this.spamBidCpd.length&&(this.fillterCpdShow(j,g[b]),q=this.cpd),1===j.iframe?(B.push(e),e=this.renderIframe("ads_zone"+s+"_banner"+j.bid,"banner"+(n+1),j.width,j.height)):e=j.renderBanner("ads_zone"+s+"_banner"+j.bid,s,Math.random(),"","banner"+(n+1))):(e=this.slotBannerDefault(p[0],n+1),""==e&&this.cpd[p[0]-1][n].length&&(h=ADS_CHECKER.in_array_position(q[p[0]-1][n][ADS_CHECKER.rand(0,this.cpd[p[0]-1][n].length-1)],t),e="string"==typeof t[h]?parseInt(t[h].replace(/_[0-9]/g,"")):t[h],j=new banner(a[e]),
0<this.spamlstCp.length&&0<this.spamBidCpd.length&&(this.fillterCpdShow(j,g[b]),q=this.cpd),1===j.iframe?(B.push(e),e=this.renderIframe("ads_zone"+s+"_banner"+j.bid,"banner"+(n+1),j.width,j.height)):e=j.renderBanner("ads_zone"+s+"_banner"+j.bid,s,Math.random(),"","banner"+(n+1)))):(e="string"==typeof t[h]?parseInt(t[h].replace(/_[0-9]/g,"")):t[h],0==e&&(j=ADS_CHECKER.array_diff(this.cpd[p[0]-1][n],this.arr7k),0!=j.length&&(1==j.length?e="string"==typeof j[0]?j[0].replace(/_[0-9]/g,""):j[0]:(e=Math.floor(Math.random()*
j.length-1),e="string"==typeof t[e]?j[e].replace(/_[0-9]/g,""):j[e]))),0!=e?(j=new banner(a[e]),0<this.spamlstCp.length&&0<this.spamBidCpd.length&&(this.fillterCpdShow(j,g[b]),q=this.cpd),1===j.iframe?(B.push(e),e=this.renderIframe("ads_zone"+s+"_banner"+j.bid,"banner"+(n+1),j.width,j.height)):e=j.renderBanner("ads_zone"+s+"_banner"+j.bid,s,Math.random(),"","banner"+(n+1))):e=this.slotBannerDefault(p[0],n+1));F+=e}c=""==F?c:c.replace("slot"+p[0]+"_content",F)}else if(z=[],j=[],e=parseInt(p[0]),!isNaN(e)){p[0]=
e;for(h=0;h<q[p[0]-1].length;h++)z.push(ADS_CHECKER.in_array_position(q[p[0]-1][h],t));for(h=0;h<A[p[0]-1].length;h++)j.push(ADS_CHECKER.in_array_position(A[p[0]-1][h],t));h=-1!=w[b].indexOf("m")?this.getMix(j,d,"z"+s+"sm"+p[0]+":"):this.getMix(z,d,"z"+s+"s"+p[0]+":");d=this.cookie;!1!==h?(e="string"==typeof t[h]?parseInt(t[h].replace(/_[0-9]/g,"")):t[h],0==e&&(j=ADS_CHECKER.array_diff(this.cpd[p[0]-1],this.arr7k),0!=j.length&&(1==j.length?e="string"==typeof j[0]?j[0].replace(/_[0-9]/g,""):j[0]:(e=
Math.floor(Math.random()*j.length-1),e="string"==typeof t[e]?j[e].replace(/_[0-9]/g,""):j[e]))),"undefined"!=typeof e&&!isNaN(parseInt(e))&&0!=e?(j=new banner(a[e]),0<this.spamlstCp.length&&0<this.spamBidCpd.length&&(this.fillterCpdShow(j,g[b]),q=this.cpd),1===j.iframe?(B.push(e),e=this.renderIframe("ads_zone"+s+"_banner"+j.bid,"banner0",j.width,j.height)):e=j.renderBanner("ads_zone"+s+"_banner"+h,s,Math.random(),"","banner0")):e=this.slotBannerDefault(p[0],"banner0")):e=this.slotBannerDefault(p[0],
n+1);c=""==e?c:c.replace("slot"+p[0]+"_content",e)}}b=this.spamBidCpd;n=0;for(p=b.length;n<p;n++)ADS_CHECKER.in_array(b[n].cid,_arAdmNotShow)&&(2==f[b[n].Idx]?this.cpd[b[n].Idx-1][b[n].sort-1]=ADS_CHECKER.array_diff(this.cpd[b[n].Idx-1][b[n].sort-1],[b[n].bid]):this.cpd[b[n].Idx-1]=ADS_CHECKER.array_diff(this.cpd[b[n].Idx-1],[b[n].bid])),ADS_CHECKER.in_array(b[n].cid,_arAdmShow)&&(2==f[b[n].Idx]?this.cpd[b[n].Idx-1][b[n].sort-1]=[b[n].bid]:this.cpd[b[n].Idx-1]=[b[n].bid]);for(b=0;b<l.length;b++)if(p=
l[b].toString().split("_"),2==f[p[0]]){F="";for(n=0;n<u[p[0]].length;n++){z=[];j=[];e=[];for(h=0;h<q[p[0]-1][n].length;h++)z.push(ADS_CHECKER.in_array_position(q[p[0]-1][n][h],t));for(h=0;h<A[p[0]-1][n].length;h++)j.push(ADS_CHECKER.in_array_position(A[p[0]-1][n][h],t));e=z;if(0<A[l[b]-1].length||0<x[l[b]])if(r=E-q[l[b]-1][n].length,0<r&&0<A[l[b]-1][n].length)for(h=0;h<r;h++)e.push("m"+(1<r?"_"+h:""));h="z"+s+"s"+l[b]+"_"+n+":";this.subCookie(d,h,0);h=this.getMix(e,d,h);d=this.cookie;-1!=h.toString().indexOf("m")||
!1===h?0==A[p[0]-1][n].length?e=this.slotBannerDefault(p[0],n+1):(h=this.getMix(j,d,"z"+s+"sm"+n+":"),d=this.cookie,e="string"==typeof t[h]?parseInt(t[h].replace(/_[0-9]/g,"")):t[h],j=new banner(a[e]),0<this.spamlstCp.length&&0<this.spamBidCpd.length&&(this.fillterCpdShow(j,[]),q=this.cpd),1===j.iframe?(B.push(e),e=this.renderIframe("ads_zone"+s+"_banner"+j.bid,"banner"+(n+1),j.width,j.height)):e=j.renderBanner("ads_zone"+s+"_banner"+j.bid,s,Math.random(),"","banner"+(n+1))):(e="string"==typeof t[h]?
parseInt(t[h].replace(/_[0-9]/g,"")):t[h],0==e&&(j=ADS_CHECKER.array_diff(this.cpd[p[0]-1][n],this.arr7k),0!=j.length&&(1==j.length?e="string"==typeof j[0]?j[0].replace(/_[0-9]/g,""):j[0]:(e=Math.floor(Math.random()*j.length-1),e="string"==typeof t[e]?j[e].replace(/_[0-9]/g,""):j[e]))),0!=e?(j=new banner(a[e]),0<this.spamlstCp.length&&0<this.spamBidCpd.length&&(this.fillterCpdShow(j,[]),q=this.cpd),1===j.iframe?(B.push(e),e=this.renderIframe("ads_zone"+s+"_banner"+j.bid,"banner"+(n+1),j.width,j.height)):
e=j.renderBanner("ads_zone"+s+"_banner"+j.bid,s,Math.random(),"","banner"+(n+1))):e=this.slotBannerDefault(p[0],n+1));F+=e}c=""==F?c:c.replace("slot"+l[b]+"_content",F)}else{z=[];j=[];for(h=0;h<q[l[b]-1].length;h++)z.push(ADS_CHECKER.in_array_position(q[l[b]-1][h],t));for(h=0;h<A[l[b]-1].length;h++)j.push(ADS_CHECKER.in_array_position(A[l[b]-1][h],t));e=z;if(0<A[l[b]-1].length||0<x[l[b]]){r=E-q[l[b]-1].length;for(h=0;h<r;h++)e.push("m"+(1<r?"_"+h:""))}h="z"+s+"s"+l[b]+":";this.subCookie(d,h,0);h=
this.getMix(e,d,h);d=this.cookie;-1!=h.toString().indexOf("m")||!1===h?0!=A[l[b]-1].length?(h=this.getMix(j,d,"z"+s+"sm"+l[b]+":"),d=this.cookie,e="string"==typeof t[h]?parseInt(t[h].replace(/_[0-9]/g,"")):t[h],j=new banner(a[e]),0<this.spamlstCp.length&&0<this.spamBidCpd.length&&(this.fillterCpdShow(j,[]),q=this.cpd),1===j.iframe?(B.push(e),e=this.renderIframe("ads_zone"+s+"_banner"+j.bid,"banner0",j.width,j.height)):e=j.renderBanner("ads_zone"+s+"_banner"+j.bid,s,Math.random(),"","banner0")):e=
this.slotBannerDefault(l[b],0):(e="string"==typeof t[h]?parseInt(t[h].replace(/_[0-9]/g,"")):t[h],0==e&&(j=ADS_CHECKER.array_diff(this.cpd[p[0]-1],this.arr7k),0!=j.length&&(1==j.length?e="string"==typeof j[0]?j[0].replace(/_[0-9]/g,""):j[0]:(e=Math.floor(Math.random()*j.length-1),e="string"==typeof t[e]?j[e].replace(/_[0-9]/g,""):j[e]))),0!=e?(j=new banner(a[e]),0<this.spamlstCp.length&&0<this.spamBidCpd.length&&(this.fillterCpdShow(j,[]),q=this.cpd),1===j.iframe?(B.push(e),e=this.renderIframe("ads_zone"+
s+"_banner"+j.bid,"banner0",j.width,j.height)):e=j.renderBanner("ads_zone"+s+"_banner"+e,s,Math.random(),"","banner0")):e=this.slotBannerDefault(l[b],"banner0"));c=""==e?c:c.replace("slot"+l[b]+"_content",e)}if(g){l=[];b=0;for(r=w.length;b<r;b++)h=w[b].replace(/_([a-z0-9]+)/gi,""),l.push(h);b=0;for(r=g.length;b<r;b++)if(u=ADS_CHECKER.array_duplicate(g[b],l),0==u.length){u=[];q=0;for(e=g[b].length;q<e;q++)2!=f[g[b][q]]&&(0<_admDefault[s][g[b][q]-1].length||0!=x[g[b][q]])&&u.push(g[b][q]);0<u.length&&
(u=u[Math.floor(Math.random()*u.length)],e=this.slotBannerDefault(u,"banner0"),c=c.replace("slot"+u+"_content",e))}}c=this.removeHtml(c);document.write(c);ADS_CHECKER.setStorage("_azs",d,"","/");0!=this.trks&&(c=ADS_CHECKER.getElementTop("ads_zone"+s+"_slot"+this.trks),0<c&&window.scrollTo(0,c));b=0;for(e=B.length;b<e;b++)c=document.getElementById("ads_zone"+s+"_banner"+B[b]),j=new banner(a[B[b]]),c=c.contentWindow?c.contentWindow.document:c.contentDocument?c.contentDocument:c.document,g="<html><head><style>body{margin:0}</style></head><body>"+
j.renderBanner("ads_zone"+s+"_banner"+B[b],s,Math.random(),"","banner"+j.sort)+"</body></html>",c.write(g),c.close()};
zone.prototype.getMix=function(a,c,d){var b=!1;if(0==a.length)return!1;if(1==a.length)return a[0];var g=this.subCookie(c,d,0),f=g.replace(d,"").split(","),l=ADS_CHECKER.array_diff(f,a),f=ADS_CHECKER.array_diff(a,f);""==g?0<a.length&&(b=ADS_CHECKER.rand(0,a.length-1),b=a[b],c+=d+b+";"):0<l.length?(c=c.replace(g+";",""),0<a.length&&(b=ADS_CHECKER.rand(0,a.length-1),b=a[b],c+=d+b+";")):0<f.length?(b=ADS_CHECKER.rand(0,f.length-1),b=f[b],c=c.replace(g+";",g+","+b+";")):(a=this.strReverse(g.replace(d,
"")),b=a.split(",")[0],c=c.replace(g+";",d+a+";"));this.cookie=c;return b};
zone.prototype.getSlotRun=function(a,c,d,b){this.subCookie(b,"Ver:",0);var g=this.style.effect,f=this.style.sort_banner_slot,l=this.style.banner_default,u=[],x=[],E=this.share,s=!1,t=[],B=[],w=this.spamBidCpd,g=this.style.effect,q=w.length,e=[];if(0<q)for(c=0;c<q;c++)ADS_CHECKER.in_array(w[c].cid,_arAdmShow)&&(ADS_CHECKER.in_array(w[c].Idx,e)||e.push(w[c].Idx),0==g[w[c].Idx]?(this.cpd[w[c].Idx-1]=[w[c].bid],this.cpm[w[c].Idx-1]=[]):0<w[c].sort&&(this.cpd[w[c].Idx-1][w[c].sort-1]=[w[c].bid],this.cpm[w[c].Idx-
1][w[c].sort-1]=[]));0<e.length&&(d=e);q=w=0;for(e=d.length;q<e;q++){var r=this.cpd[d[q]-1].join(",").replace(/,/g,""),p=this.cpm[d[q]-1].join(",").replace(/,/g,"");if(""!=r){x.push(d[q]);var h=0;if(2==g[d[q]])for(r=0;r<f[d[q]].length;r++)h=Math.max(h,this.cpd[d[q]-1][r].length);else h=this.cpd[d[q]-1].length;for(r=0;r<h;r++)t.push(d[q]+(1<h?"_"+r:""));w+=h}if(""!=p){p=0;u.push(d[q]);if(2==g[d[q]])for(r=0;r<f[d[q]].length;r++)p=Math.max(p,this.cpm[d[q]-1][r].length);else p=this.cpm[d[q]-1].length;
for(r=0;r<p;r++)B.push(d[q]+(1<p?"_"+r:""))}if(q==e-1)if(p=this.subCookie(b,"z"+a+"R"+c+":",0),0<w){h=t;if(0<u.length)for(r=0;r<E-w;r++)t.push(d[q]+"_m_"+r);var A=p.replace("z"+a+"R"+c+":","").split(",");1==t.length||""==p||A.length>t.length||0!=ADS_CHECKER.array_diff(A,t).length?(""!=p&&(b=b.replace(p+";","")),r=ADS_CHECKER.rand(0,h.length-1),s=h[r],1<t.length&&(b+="z"+a+"R"+c+":"+h[r]+";")):A.length==t.length&&0==ADS_CHECKER.array_diff(A,t).length&&0==ADS_CHECKER.array_diff(t,A).length?(s=this.strReverse(p.replace("z"+
a+"R"+c+":","")),r=s.split(","),b=b.replace(p+";","z"+a+"R"+c+":"+s+";"),-1!=r[0].indexOf("m")?(b=this.choseMix(a,c,B,b),s=b+"_m",b=this.cookie):s=r[0]):""==p?(r=ADS_CHECKER.rand(0,h.length-1),s=h[r],b+="z"+a+"R"+c+":"+h[r]+";"):(r=ADS_CHECKER.array_diff(A,h),s=ADS_CHECKER.array_diff(t,A),h=ADS_CHECKER.array_diff(h,A),0==r.length&&0!=h.length?(r=ADS_CHECKER.rand(0,h.length-1),b=b.replace(p+";",p+","+h[r]+";"),s=h[r]):(r=ADS_CHECKER.rand(0,s.length-1),b=b.replace(p+";",p+","+s[r]+";"),s=b=this.choseMix(a,
c,B,b),b=this.cookie))}else if(0==w&&0<u.length)b=this.choseMix(a,c,B,b),s=b+"_m",b=this.cookie;else if(0==w&&0==u.length){p=[];r=0;for(h=d.length;r<h;r++)0!=l[d[r]]&&p.push(d[r]);0<p.length&&(s=p[ADS_CHECKER.rand(0,p.length-1)]+"_d")}}this.cookie=b;return s};
zone.prototype.choseMix=function(a,c,d,b){var g=this.subCookie(b,"z"+a+"m"+c+":",0);if(1==d.length)return""!=g&&(b=b.replace(g+";","")),this.cookie=b,d[0];var f=g.replace("z"+a+"m"+c+":","").split(",");if(f.length>d.length||""!=f[0]&&0!=ADS_CHECKER.array_diff(f,d).length)return""!=g&&(b=b.replace(g+";","")),this.cookie=b,d[ADS_CHECKER.rand(0,d.length-1)];if(f.length==d.length&&0==ADS_CHECKER.array_diff(f,d).length&&0==ADS_CHECKER.array_diff(d,f).length)return d=this.strReverse(g.replace("z"+a+"m"+
c+":","")),f=d.split(","),this.cookie=b=b.replace(g+";","z"+a+"m"+c+":"+d+";"),f[0];d=ADS_CHECKER.array_diff(d,f);f=ADS_CHECKER.rand(0,d.length-1);this.cookie=b=""!=g?b.replace(g+";",g+","+d[f]+";"):b+("z"+a+"m"+c+":"+d[f]+";");return d[f]};
zone.prototype.drawEmpty=function(){for(var a=[],c=this.style.slots_rotate,d=this.style.effect,b=this.style.html,g=this.style.banner_default,f=this.zoneid,l=0;l<this.style.slot;l++)a[l]=l+1;if(c)for(var l=0,u=c.length;l<u;l++){for(var a=ADS_CHECKER.array_diff(a,c[l]),x=[],E=0,s=c[l].length;E<s;E++){var t=!1;2!=d[c[l][E]]&&0<_admDefault[f][c[l][E]-1].length&&(x.push(c[l][E]),t=!0);0!=g[c[l][E]]&&!1===t&&x.push(c[l][E])}0<x.length&&a.push(x[ADS_CHECKER.rand(0,x.length-1)])}l=0;for(u=a.length;l<u;l++)c=
2!=d[a[l]]?this.slotBannerDefault(a[l],0):this.slotAllDefault(a[l]),b=""==c?b:b.replace("slot"+a[l]+"_content",c);b=this.removeHtml(b);document.write(b)};zone.prototype.initZone=function(a){a?this.getBannerRun(a):this.drawEmpty();return!1};
zone.prototype.slotBannerDefault=function(a,c){var d=this.style.effect;if(2!=d[a]&&(0===c||"banner0"==c)){if(0<_admDefault[this.zoneid][a-1].length)return d=Math.floor(_admDefault[this.zoneid][a-1].length*Math.random()),d=new banner(_admDefault[this.zoneid][a-1][d]),d.renderBanner("ads_zone"+this.zoneid+"_banner"+c,this.zoneid,Math.random(),"","banner"+c)}else if(2===d[a]&&0<_admDefault[this.zoneid][a-1][c-1].length)return d=Math.floor(_admDefault[this.zoneid][a-1][c-1].length*Math.random()),d=new banner(_admDefault[this.zoneid][a-
1][c-1][d]),d.renderBanner("ads_zone"+this.zoneid+"_banner"+c,this.zoneid,Math.random(),"","banner"+c);return 0!=this.style.banner_default[a]&&(d=this.style.banner_default[a],d=new banner({bannertype:0,bid:0,title:"",type:d.type,link:d.link,src:d.src,width:d.width,height:d.height,created:null,expired:null,slotIdx:a,attr:null,terms:d.terms,clicks:0,views:0,cpname:"",counter:!1,iframe:0,fix_ie:0,sort:0,link_clicks:null,link_views:null}),d.process(),d.bool)?d.renderBanner("ads_zone"+this.zoneid+"_banner"+
c,this.zoneid,Math.random(),"","banner"+c):""};zone.prototype.slotAllDefault=function(a){for(var c=this.style.sort_banner_slot[a].length,d="",b=0;b<c;b++)d+=this.slotBannerDefault(a,b+1);return d};zone.prototype.subCookie=function(a,c,d){c=a.indexOf(c,d);d=a.length-1;if(-1!=c){var b=a.indexOf(";",c);-1==b&&(b=d);return a.substring(c,b)}return""};zone.prototype.strReverse=function(a){var c=a.indexOf(","),d=a.length;return-1==c?a:a.substring(c+1,d)+","+a.substring(0,c)};
zone.prototype.addBanners=function(a){var c=this.style.slot,d='<div id="ads_zone'+this.zoneid+'">'+this.style.html.replace(/id="slot/g,'id="ads_zone'+this.zoneid+"_slot")+"</div>";this.style.html='<div id="ads_zone'+this.zoneid+'">'+this.style.html.replace(/id="slot/g,'id="ads_zone'+this.zoneid+"_slot")+"</div>";this.style.css&&this.bindCSS(this.style.css);if(this.style&&0<this.style.slot){this.slots=[];for(var b=0;b<=c;b++)this.slots[b]=""}if(!this.initZone(a,d))return!1};
zone.prototype.getSizeStr=function(){this.width=0<parseInt(this.width)?"width:"+this.width+"px;":"";this.height=0<parseInt(this.height)?"height:"+this.height+"px;":""};zone.prototype.getZoneTag=function(){return"ads_zone"+this.zoneid};zone.prototype.append2slot=function(a,c){var d="slot"+c+"_content";this.style.html=this.style.html.replace(d,a+d)};zone.prototype.drawZoneTag=function(){};zone.prototype.hideEmptyZone=function(){};
zone.prototype.bindCSS=function(a){var c=document.createElement("style");c.type="text/css";document.getElementsByTagName("head")[0].appendChild(c);c.styleSheet?c.styleSheet.cssText=a:c.appendChild(document.createTextNode(a))};

if(ADS_Location=='3'){
	imgHost=imgHost.replace("admicro2.","admicro2-hcm.");
	admImgHost=true;
}


var _admTVCVideo=[];
function admParamTvc(){var a=0,b=0;void 0!=window.ADS_CHECKER&&"undefined"!=window.ADS_CHECKER&&(a=ADS_CHECKER.getQuery("_itvc"),a=""==a?0:parseInt(a),b=ADS_CHECKER.getCookie("__R"),b=""==b?0:parseInt(b)); if(_admTVCVideo.length>0){a=0;} if(a!=0){_admTVCVideo.push(a);}   return a+";"+b};


(function(){var d=!1,c=[];if(!(window.AdmonDomReady&&"function"==typeof window.AdmonDomReady)){var a=function(){if(!document.body)return setTimeout(a,13);for(var b=0;b<c.length;b++)c[b]();c=[]};window.AdmonDomReady=function(b){c.push(b);if("complete"==document.readyState)a();else if(!d){if(document.addEventListener){var e=function(){document.removeEventListener("DOMContentLoaded",e,!1);a()};document.addEventListener("DOMContentLoaded",e,!1);window.addEventListener("load",a,!1)}else if(document.attachEvent){var f=
function(){"complete"===document.readyState&&(document.detachEvent("onreadystatechange",f),a())};document.attachEvent("onreadystatechange",f);window.attachEvent("onload",a);b=!1;try{b=null==window.frameElement}catch(h){}if(document.documentElement.doScroll&&b){var g=function(){if(0!=c.length){try{document.documentElement.doScroll("left")}catch(b){setTimeout(g,1);return}a()}};g()}}d=!0}}}})();
function admaddEventListener(d,c,a){"addEventListener"in d?d.addEventListener(c,a):"attachEvent"in d&&d.attachEvent("on"+c,a)};


var jsTimeout=new Number,jsTimeDelay=60,jsAcceleration=0.2,jsVelocity=3;function jsAnimate(a,d,c){var b=new Number,b=[],b=String(document.getElementById(a).style[d]).split("px"),b=parseInt(b[0]);clearTimeout(jsTimeout);parseInt(c)>b?jsTimeout=setTimeout('animateProcess("'+a+'", "'+d+'", "increase", "'+b+'", "'+c+'", 1)',jsTimeDelay):parseInt(c)<b&&(jsTimeout=setTimeout('animateProcess("'+a+'", "'+d+'", "increase", "'+b+'", "'+c+'", 1)',jsTimeDelay))}
function animateProcess(a,d,c,b,f,g){clearTimeout(jsTimeout);var h=jsAcceleration*Math.pow(parseInt(g),2)/2+jsVelocity*parseInt(g),e=new Number;switch(c){case "increase":e=parseInt(b)+parseInt(h);e>=parseInt(f)?document.getElementById(a).style[d]=f+"px":(document.getElementById(a).style[d]=e+"px",g++,jsTimeout=setTimeout('animateProcess("'+a+'", "'+d+'", "'+c+'", "'+e+'", "'+f+'", '+g+")",jsTimeDelay));break;case "decrease":e=parseInt(b)-parseInt(h),e<=parseInt(f)?document.getElementById(a).style[d]=
f+"px":(document.getElementById(a).style[d]=e+"px",g++,jsTimeout=setTimeout('animateProcess("'+a+'", "'+d+'", "'+c+'", "'+e+'", "'+f+'", '+g+")",jsTimeDelay))}}function hookExpand(a,d,c){a=document.getElementById(a);if(null!=a){if(c){for(var c=a.offsetTop,b=a;b.offsetParent&&b.offsetParent!=document.body;)b=b.offsetParent,c+=b.offsetTop;window.scrollTo(0,c)}a.style.clip=d}};


var _arrCpmRun=[0],_arrCpm=[0];function cpmzone(a){this.zid=a;this.banIframe=[]}
cpmzone.prototype.renderIframe=function(){for(var a=this.banIframe,c=0,d=a.length;c<d;c++){var b=document.getElementById("cpmzone_"+this.zid+"_"+c+"_"+a[c].bid),b=b.contentWindow?b.contentWindow.document:b.contentDocument?b.contentDocument:b.document;b.write("<head><style>body{margin:0}</style></head><body>"+('<script type="text/javascript">function cpmtkc(){var img=new Image(); img.src=\''+a[c].click+"';}\x3c/script>")+a[c].src)+"</body>";b.close()}};
cpmzone.prototype.logging=function(a,c,d){var b="http://",e="";c?(b+="logging.admicro.vn/_adv.gif",e=d?encodeURIComponent(b+"?adm_domain="+escape(document.URL)+"&adm_campaign="+(a.cid?a.cid:"")+"&adm_aditem="+a.bid+"&adm_zoneid="+this.zid+"&adm_channelid=-1"):b+"?adm_domain="+escape(document.URL)+"&adm_campaign="+(a.cid?a.cid:"")+"&adm_aditem="+a.bid+"&adm_zoneid="+this.zid+"&adm_channelid=-1"):(b+="logging.admicro.vn/_adc.html",e=d?encodeURIComponent(b+"?adm_domain="+escape(document.URL)+"&adm_campaign="+
(a.cid?a.cid:"")+"&adm_aditem="+a.bid+"&adm_zoneid="+this.zid+"&adm_channelid=-1&adm_rehttp="+escape(a.link)):b+"?adm_domain="+escape(document.URL)+"&adm_campaign="+(a.cid?a.cid:"")+"&adm_aditem="+a.bid+"&adm_zoneid="+this.zid+"&adm_channelid=-1&adm_rehttp="+encodeURIComponent(a.link));return e};
cpmzone.prototype.renderBanner=function(a){var c="";switch(a.type){case "gif":case "jpeg":case "png":case "jpg":c+=this.renderBannerImage(a);break;case "swf":var d=!0;void 0!=window.ADS_CHECKER&&"undefined"!=window.ADS_CHECKER&&(d=ADS_CHECKER.flash);d?c+=this.renderBannerFlash(a):(a.src=a.src_bk,c+=this.renderBannerImage(a));break;case "html":c+=a.src;break;case "iframe":d=this.banIframe.length,this.banIframe[d]={src:a.src,bid:a.bid,click:this.logging(a,!1,!1).replace(/&adm_rehttp=(.*)$/,"&adm_rehttp=")},
c+='<iframe style="border:none;" marginheight="0" align="top" scrolling="No" frameborder="0" hspace="0" vspace="0" id="cpmzone_'+this.zid+"_"+d+"_"+a.bid+'" width="'+a.width+'" height="'+a.height+'" ></iframe>'}document.images?(new Image).src=this.logging(a,!0,!1):c+='<div style="background:url('+this.logging(a,!0,!1)+'); height:0; width:0;position:absolute;border:none" ><span style="height:0; width:0"></span></div>';return c+this.renderLinkViews(a.link_views)};
cpmzone.prototype.renderLinkViews=function(a){var c="";null!=a&&(document.images?(new Image).src=a:c+='<div style="position:absolute;background:url('+a+');height:0; width:0" ><span style="height:0; width:0"></span></div>');return c};
cpmzone.prototype.renderBannerImage=function(a){var c='<img border="0" id="cpm'+this.zid+'" src="'+(admImgHost?a.src.replace("admicro2.","admicro2-hcm."):a.src)+'"'+(a.width?' width="'+a.width+'"':"")+(a.height?' height="'+a.height+'"':""),c=c+"  />";return a.link?'<a href="'+this.logging(a,!1,!1)+'" target="_blank">'+c+"</a>":c};
cpmzone.prototype.renderBannerFlash=function(a){var c="",d=a.link?"alink1="+this.logging(a,!1,!0)+"&amp;atar1=_blank":"";""!=d&&(c+=' flashvars="'+d+'"');return'<embed  src="'+(admImgHost?a.src.replace("admicro2.","admicro2-hcm."):a.src)+'" height="'+a.height+'" align="middle" width="'+a.width+'" pluginspage="http://www.macromedia.com/go/getflashplayer" type="application/x-shockwave-flash" '+c+' allowscriptaccess="always" wmode="transparent" quality="high" />'};
cpmzone.prototype.getData=function(a){var c=[],d=0,b=0,e="",h="",f=","+_arrCpmRun.join(",")+",",m=-1,k="",j=[],n=[],p=!0;void 0!=window.ADS_CHECKER&&"undefined"!=window.ADS_CHECKER&&(p=ADS_CHECKER.flash,d=parseInt(ADS_CHECKER.getQuery("i")),e=ADS_CHECKER.getCookie("__R"),h=ADS_CHECKER.getCookie("__RC"));for(var e=","+e+",",h=","+h+",",d=isNaN(d)?0:d,g=0,q=a.length;g<q;g++){var l=!1;if(-1==f.indexOf(","+a[g].bid+",")){var l=","+a[g].l+",",r=/,[1|2|3],[1|2|3],[1|2|3],/g,l=-1!=l.indexOf(",,")||-1!=l.indexOf(",0,")||
r.test(l)||-1!=l.indexOf(e)||-1!=l.indexOf(h);p||"swf"==a[g].type&&""==a[g].src_bk&&(l=!1);"undefined"!=typeof __arCPM4K&&void 0!=window.ADS_CHECKER&&"undefined"!=window.ADS_CHECKER&&ADS_CHECKER.in_array(a[g].bid,__arCPM4K)&&(191479!=a[g].bid&&192146!=a[g].bid&&197484!=a[g].bid)&&(l=!1);l&&(b=d==a[g].bid?a[g].bid:b,m=d==a[g].bid?g:m,k=d==a[g].bid?a[g].width+"x"+a[g].height:k,c.push(g),1==this.db&&(300==a[g].width&&250==a[g].height||468==a[g].width&&90==a[g].height)?g!=m&&j.push(g):1==this.db&&(300==a[g].width&&600==
a[g].height||980==a[g].width&&90==a[g].height)&&n.push(g))}}if(0==c.length)return c;this.bz=b;if(1==this.db&&1<c.length){if("980x90"==k||"300x600"==k)return[m];if("300x250"==k||"468x90"==k)return 2>=j.length?j:[b,j[Math.floor(j.length*Math.random())]];if("980x90"==this.size||"300x600"==this.size){if(0<j.length&&0<n.length)return 0.5<=Math.random()?j:n;if(0<j.length)return j;if(0<n.length)return n}}else return 0!=b?[m]:c};
cpmzone.prototype.renderBannerExp=function(a){var c="";switch(a.type){case "gif":case "jpeg":case "png":case "jpg":case "swf":var d=!0;void 0!=window.ADS_CHECKER&&"undefined"!=window.ADS_CHECKER&&(d=ADS_CHECKER.flash);d?(c+=this.renderBannerFlashExp(a),document.images?(new Image).src=this.logging(a,!0,!1):c+='<div style="background:url('+this.logging(a,!0,!1)+'); height:0; width:0;position:absolute;border:none" ><span style="height:0; width:0"></span></div>'):("swf"==a.type&&(a.src=a.src_bk),c+=this.renderBannerImage(a));
break;case "html":c+=a.src,document.images?(new Image).src=this.logging(a,!0,!1):c+='<div style="background:url('+this.logging(a,!0,!1)+'); height:0; width:0;position:absolute;border:none" ><span style="height:0; width:0"></span></div>'}c+=this.renderLinkViews(a.link_views);d="";if("300"==a.width)return d='<div id="rick_banner'+a.bid+'_1" style="position: relative; width: 300px; height: 250px;"><div id="rick_banner'+a.bid+'" style="position: absolute;top: 0px; right: 0px; clip: rect(0px, 980px, 250px, 680px); z-index: 1000;">',
d+c+"</div></div>";d="468";"980"==a.width&&(d="0");d='<div id="rick_banner'+a.bid+'" style="position: relative; height:'+a.height+"px;  width:"+a.width+"px;  bottom: 0px; right: 0px; clip: rect(0px, 980px, 90px, "+d+'px); z-index: 1000;">';return d+c+"</div>"};
cpmzone.prototype.renderBannerFlashExp=function(a){var c="",d=a.link?"alink1="+this.logging(a,!1,!0)+"&amp;atar1=_blank":"",b="rick_banner"+a.bid;""!=d&&(c+=' flashvars="div_id='+b+"&"+d+"&file1="+a.src+"&file2="+a.src_exp+"&size="+a.width+"x"+a.height+'"');d=3;"300"==a.width&&(d=7);return'<embed height="300" align="middle" width="980" quality="high" wmode="transparent" allowscriptaccess="always" type="application/x-shockwave-flash" pluginspage="http://www.macromedia.com/go/getflashplayer" '+c+' src="http://corejs.com/cpm(7k-4k)/expand7k_v1.swf?v='+
d+'"/>'};cpmzone.prototype.Shuffle=function(a){for(var c,d,b=a.length;b;c=parseInt(Math.random()*b),d=a[--b],a[b]=a[c],a[c]=d);return a};
cpmzone.prototype.show=function(a){this.size=a.size;this.db=(this.db=a.is_db)?this.db:0;var c=document.domain,c=c.replace("www.",""),d=c.split("."),b="",e="",c=document,h=c.createElement("style");if("undefined"==typeof f)var f="http://admicro2.vcmedia.vn/adt/cpc/";"4k"==a.type&&"160x600"==a.size?(e="#cpmzone{clear:both;width:160px;height:auto;text-align:left;overflow:hidden;margin:0 auto}#cpmzone *{text-decoration:none;font-family:tahoma,arial!important;_font-family:tahoma, arial;font-size:11px;color:#333;text-transform:none!important;_text-transform:none;margin:0;padding:0}#cpmzone .ssvzContent{clear:both;overflow:hidden;background:#fff}#cpmzone .ssvzContent .ssvzMid{background:#FFF;height:auto}#cpmzone .ssvzHeader{background:url("+f+
"ssvborder.png) repeat-x 5px -18px;height:21px;line-height:21px}#cpmzone .ssvHeaderBr{background:url("+f+"ssvtop.png) repeat-y 0 0;clear:both;overflow:hidden}#cpmzone .ssvzLogo{border:0;width:140px;height:21px;line-height:21px;background:url("+f+"ssvtop.png) no-repeat -3px 0;margin:0;padding:0}#cpmzone .ssvzBuy{border:0;width:140px;height:21px;background:url("+f+"ssvtop.png) no-repeat -3px -21px}#cpmzone #cpmzone_items{clear:both;margin:0}#cpmzone_items .adv_items{clear:both;height:216px;overflow:hidden;padding-top:5px;padding-right:7px;margin-left:7px}#cpmzone_items .ssvzBorder{background:#e5e5e5;height:1px}#cpmzone .ssvzclear,#cpmzone_items .adv_items .ssvzimage{clear:both}",
b=b+'<div class="ssvHeaderBr"><div class="ssvHeaderBrRight"><div class="ssvzHeader">'+('<a title="Mua qu\u1ea3ng c\u00e1o"  href="http://admarket.admicro.vn/?utm_source=box_'+d[0]+'&utm_medium=banner&utm_campaign=PR06201" target="_blank"><img vspace="0" hspace="0" class="ssvzBuy" src="http://admicro2.vcmedia.vn/adt/cpc/zoneimages/spacer.gif" border="0" align="right" /></a></div></div></div>'),b+='<div class="ssvzContent"><div class="ssvzRight"><div class="ssvzMid">',b+='<div id="cpmzone_items"></div><div class="ssvzclear"><span></span></div>',
b+="</div></div></div>",b+='<div class="ssvHeaderBrRight"><div class="ssvzHeader"><div class="ssvHeaderBrRight"> ',b+='<a title="Mua qu\u1ea3ng c\u00e1o" href="http://admarket.admicro.vn/?utm_source=box_'+d[0]+'&utm_medium=banner&utm_campaign=PR06201" target="_blank"><img class="ssvzLogo" vspace="0" hspace="0" border="0" align="left" src="http://admicro2.vcmedia.vn/adt/cpc/zoneimages/spacer.gif"></a></div></div></div>'):"4k"==a.type&&"200x167"==a.size?e="#cpmzone{clear:both;width:200px;height:auto;text-align:left;margin:0 auto} #cpmzone img, #cpmzone embed, #cpmzone object{width:200px; height:167px;}":
("4k"==a.type||"7k"==a.type)&&0==a.is_db?e="#cpmzone{clear:both;text-align:left;margin:0 auto}":"7k"==a.type&&"980x90"==a.size?(e="#cpmzone{clear:both;width:980px;height:auto;text-align:left;margin:0 auto}#cpmzone_banner_left{float:left; width:468px;}#cpmzone_banner_right{float:right; width:468px;},#cpmzone_banner{clear:both; width:980px; margin:0 auto;}",b+='<div id="cpmzone_items"></div>'):"7k"==a.type&&"300x600"==a.size&&(e="#cpmzone{clear:both;width:300px;height:auto;text-align:left;margin:0 auto}#cpmzone_banner{clear:both;}",
b+='<div id="cpmzone_items"></div>');b=b.replace(/cpmzone/g,"cpmzone_"+this.zid);h.type="text/css";c.getElementsByTagName("head")[0].appendChild(h);e=e.replace(/cpmzone/g,"cpmzone_"+this.zid);h.styleSheet?h.styleSheet.cssText=e:h.appendChild(c.createTextNode(e));f=c.getElementById("cpmzone_"+this.zid);try{f?(f.innerHTML=b,0<this.banIframe.length&&this.renderIframe()):c.write('<div id="cpmzone_'+this.zid+'">'+b+"</div>")}catch(m){}f=this.getData(a.lst);b="";d=a.df;if(0<f.length)if(f=this.Shuffle(f),
"4k"==a.type)b+=this.renderBanner(a.lst[f[0]]),"160x600"==a.size&&(1<f.length?b=b+'<div style="clear:both; height:10px;"><span></span></div>'+this.renderBanner(a.lst[f[0]]):0<a.df.length&&(b+='<div style="clear:both; height:10px;"><span></span></div>',d=this.Shuffle(d),b+=this.renderBanner(d[0])));else{if("7k"==a.type)if("300x600"==a.size||"980x90"==a.size){for(var k=!1,h=e=0,j=f.length;h<j;h++)184455==a.lst[h].bid&&h!=f[0]&&(e=h,k=!0);if(!0==k){k=f[0];h=1;for(j=f.length;h<j;h++)f[h]==e&&(f[0]=e,
f[h]=k)}e=a.lst[f[0]];"300x600"==a.size?(b=""!=e.src_exp?b+this.renderBannerExp(e):b+this.renderBanner(e),600!=e.height&&(1<f.length?(b+='<div style="clear:both; height:10px;"><span></span></div>',e=a.lst[f[1]],b=""!=e.src_exp?b+this.renderBannerExp(e):b+this.renderBanner(e)):0<a.df.length&&(b+='<div style="clear:both; height:10px;"><span></span></div>',d=this.Shuffle(d),e=d[0],b+=this.renderBanner(e)))):980==e.width?b=""!=e.src_exp?b+this.renderBannerExp(e):b+this.renderBanner(e):(b=""!=e.src_exp?
b+('<div id="cpmzone_'+this.zid+'_banner_left">'+this.renderBannerExp(e)+"</div>"):b+('<div id="cpmzone_'+this.zid+'_banner_left">'+this.renderBanner(e)+"</div>"),1<f.length?(e=a.lst[f[1]],b=""!=e.src_exp?b+('<div id="cpmzone_'+this.zid+'_banner_right">'+this.renderBannerExp(e)+"</div>"):b+('<div id="cpmzone_'+this.zid+'_banner_right">'+this.renderBanner(e)+"</div>")):0<a.df.length&&(d=this.Shuffle(d),e=d[0],b+='<div id="cpmzone_'+this.zid+'_banner_right">'+this.renderBanner(e)+"</div>"))}else e=
a.lst[f[0]],b=""!=e.src_exp?b+this.renderBannerExp(e):b+this.renderBanner(e)}else"4k"==a.type&&"160x600"==a.size?(f=document.getElementById("cpmzone_"+this.zid),f.style.display="none"):"980x90"==a.size||"300x600"==a.size?0<d.length&&(1<d.length?"980x90"==a.size?(b+='<div id="cpmzone_'+this.zid+'_banner_left">'+this.renderBanner(d[0])+"</div>",b+='<div id="cpmzone_'+this.zid+'_banner_right">'+this.renderBanner(d[1])+"</div>"):(b+=this.renderBanner(a.lst[f[0]]),b+='<div style="clear:both; height:10px;"><span></span></div>',
b+=this.renderBanner(a.lst[f[1]])):"980x90"==a.size?(b+='<div id="cpmzone_'+this.zid+'_banner_left">'+this.renderBanner(d[0])+"</div>",b+='<div id="cpmzone_'+this.zid+'_banner_right">'+this.renderBanner(d[0])+"</div>"):(b+=this.renderBanner(a.lst[f[0]]),b+='<div style="clear:both; height:10px;"><span></span></div>',b+=this.renderBanner(a.lst[f[0]]))):0<d.length?b+=this.renderBanner(d[Math.floor(Math.random()*d.length)]):(f=document.getElementById("cpmzone_"+this.zid),f.style.display="none");("4k"==
a.type&&"160x600"==a.size||"7k"==a.type&&"300x600"==a.size||"7k"==a.type&&"980x90"==a.size?c.getElementById("cpmzone_"+this.zid+"_items"):c.getElementById("cpmzone_"+this.zid)).innerHTML=b;0<this.banIframe.length&&this.renderIframe()};

function adoverlay(){if(!_ovelayShow)return null;this.domain="http://"+document.domain+"/";this.Shuffle=function(b){for(var c,d,e=b.length;e;c=parseInt(Math.random()*e),d=b[--e],b[e]=b[c],b[c]=d);return b};this.logging=function(b,c,d){return c?"http://logging.admicro.vn/_adc.html?"+b:d?"http://logging.admicro.vn/_zc.1.gif?"+b:"http://logging.admicro.vn/_adv.gif?"+b};this.FlashText=function(b){return b.replace(/<(span|strong|b)([^>]*)>(.*?)<\/(span|strong|b)>/g,"$3")};if("undefined"!=typeof _ssv_tvc){var h=
_ssv_tvc.z,c=_ssv_tvc.data,g=[],d=[],e=",0,",i=",0,";if("undefined"!=typeof ADS_CHECKER)var e=a=ADS_CHECKER.getCookie("__R"),b=ADS_CHECKER.getCookie("__RC"),e=""==e?",0,":","+e+",",i=""==b?",0,":","+b+",";for(var b=0,j=c.length;b<j;b++){var f=","+c[b].l+",";(-1!=f.indexOf(",1,2,3,")||-1!=f.indexOf(",3,2,1,")||-1!=f.indexOf(",,")||-1!=f.indexOf(e)||-1!=f.indexOf(i))&&d.push(c[b])}c=[];d=this.Shuffle(d);if(3>=d.length)c=d;else for(b=0;3>b;b++)c.push(d[b]);if(c)for(b=0;b<c.length;b++)c[b].title=this.FlashText(c[b].title),
c[b].content=this.FlashText(c[b].content),d={},d.adThumb=c[b].image,d.adTitle=c[b].title,d.adContent=c[b].content,d.adLink=this.logging("adm_domain="+encodeURIComponent(document.URL)+"&adm_campaign="+c[b].cid+"&adm_aditem="+c[b].bid+"&adm_zoneid="+h+"&adm_channelid=-1&adm_rehttp="+encodeURIComponent(c[b].link+(-1!=c[b].descr.indexOf("muachung.vn")?"?ref="+encodeURIComponent(document.URL)+"&bi="+c[b].bid+"&ci="+c[b].cid:"")),!0,!0),d.adDomain=c[b].descr,d.adView=this.logging("adm_aditem="+c[b].bid+
"&adm_campaign="+c[b].cid+"&adm_channelid=-1&adm_domain="+encodeURIComponent(document.URL)+"&adm_zoneid="+h,!1,!1),g.push(d);return 0<g.length?g:null}return null};


var _preloadRun={preroll:{cpc:[],cpm:[]},postroll:{cpc:[],cpm:[]}};


var wPrototype={wdHeight:function(){var a,b=document;"number"==typeof window.innerWidth?a=window.innerHeight:b.documentElement&&b.documentElement.clientHeight?a=b.documentElement.clientHeight:b.body&&b.body.clientHeight&&(a=b.body.clientHeight);return a},wdWidth:function(){var a,b=document;"number"==typeof window.innerWidth?a=window.innerWidth:b.documentElement&&b.documentElement.clientWidth?a=b.documentElement.clientWidth:b.body&&b.body.clientWidth&&(a=b.body.clientWidth);return a},getElementTop:function(a){var b=
document;if(b.getElementById)var c=b.getElementById(a);else b.all&&(c=b.all[a]);if(null!=c){yPos=c.offsetTop;for(tempEl=c.offsetParent;null!=tempEl;)yPos+=tempEl.offsetTop,tempEl=tempEl.offsetParent;return yPos}return 150},getElementWidth:function(a){return document.getElementById(a).clientWidth},getElementLeft:function(a){var b,c=document;c.getElementById?b=c.getElementById(a):c.all&&(b=c.all[a]);a=b.offsetLeft;for(b=b.offsetParent;null!=b;)a+=b.offsetLeft,b=b.offsetParent;return a},scrollTop:function(){var a=
document,b=a.body.scrollTop;0==b&&(b=window.pageYOffset?window.pageYOffset:a.body.parentElement?a.body.parentElement.scrollTop:0);return b},scrollLeft:function(){var a=document,b=window.pageXOffset?window.pageXOffset:0,c=a.documentElement?a.documentElement.scrollLeft:0,a=a.body?a.body.scrollLeft:0,b=b?b:0;if(c&&(!b||b>c))b=c;return a&&(!b||b>a)?a:b},bdWidth:function(){var a=document;return bodyWidth=Math.max(Math.max(a.body.scrollWidth,a.documentElement.scrollWidth),Math.max(a.body.offsetWidth,a.documentElement.offsetWidth),
Math.max(a.body.clientWidth,a.documentElement.clientWidth))},bdHeight:function(){var a=document;return Math.max(Math.max(a.body.scrollHeight,a.documentElement.scrollHeight),Math.max(a.body.offsetHeight,a.documentElement.offsetHeight),Math.max(a.body.clientHeight,a.documentElement.clientHeight))}};
//bannerdefault

document.write('<script language="javascript" src="http://admicro1.vcmedia.vn/cpc/ssvzone_default.js"></script>');

function _admloadJs(c,a){var b=document.createElement("script");document.getElementsByTagName("head")[0].appendChild(b);b.onload=function(){"function"==typeof a&&a();a=null};b.onreadystatechange=function(){if(4==b.readyState||"complete"==b.readyState)"function"==typeof a&&a(),a=null};b.src=c}

(function(){var a=document.createElement("script");a.type="text/javascript";a.async=!0;a.src="http://admicro1.vcmedia.vn/core/adm_tracking.js?id="+Math.random();var b=document.getElementsByTagName("script")[0];b.parentNode.insertBefore(a,b)})();var _admSticky=[],_admStickyId=[],_admFSticky=200,_admAppBanner=[],admURL=document.URL,htmladstest="";


if("undefined"==typeof __arCPCBL)var __arCPCBL=[];var arrCPCDf={city:[],area:[],check:!1};Array.prototype.indexOf||(Array.prototype.indexOf=function(r,l){var d=this.length,a=Number(l)||0,a=0>a?Math.ceil(a):Math.floor(a);for(0>a&&(a+=d);a<d;a++)if(a in this&&this[a]===r)return a;return-1});
(function(r){var l=function(){},d=l.prototype;d.trkItem=[];d.arrFav=[];d.df=[];d.arrCity=[];d.arrArea=[];d.zoneid=-1;d.template="";d.css="";d.link3rd=[];d.rand_limit=4;d.arrayArea=function(a){for(var b=[],c=[],e=a.length,f=/,[1|2|3],[1|2|3],[1|2|3],/g,d=","+ADS_Location+",",g=","+ADS_City+",",k=0;k<e;k++){var h=","+a[k].l+",",p=","+a[k].la+",";f.test(h)||",,"==h||-1!=h.indexOf(d)||-1!=h.indexOf(g)?b.push(a[k]):-1!=p.indexOf(d)&&c.push(a[k])}return{arrCity:b,arrArea:c}};d.rankMulti=function(a){for(var b=
0,c=a.length;b<c;b++)a[b].r=5*parseInt(a[b].r);return a};d.init=function(a){var b=[],c=ADS_CHECKER.getQuery("i"),e=[],f=!1,d=/,[1|2|3],[1|2|3],[1|2|3],/g,g=","+ADS_Location+",",k=","+ADS_City+",",h=!1,p=[],h=!("1"==ADS_City||"2"==ADS_City||"3"==ADS_City||"4"==ADS_City||"5"==ADS_City||"0"==ADS_City||70<parseInt(ADS_City)),c=""==c&&isNaN(c)?0:parseInt(c),q;for(q in a){var m=this.toArray(a[q]),n;for(n in m)if(m[n].bid==c&&!1==f&&(f=!0,this.trkItem.push(m[n])),h&&"103"!=q&&"203"!=q&&"201"!=q&&"202"!=
q){var l=","+m[n].l+",";(d.test(l)||",,"==l||-1!=l.indexOf(g)||-1!=l.indexOf(k))&&!ADS_CHECKER.in_array(m[n].bid,__arCPCBL)&&!ADS_CHECKER.in_array(m[n].bid,p)?(p.push(m[n].bid),b.push(m[n])):!ADS_CHECKER.in_array(m[n].bid,__arCPCBL)&&!ADS_CHECKER.in_array(m[n].bid,p)&&(e.push(m[n]),p.push(m[n].bid))}}h&&(this.arrCity=b,this.arrArea=e)};d.sortRank=function(a){for(var b={},c=a.length,e=0;e<c-1;e++)for(var f=e+1;f<c;f++)parseInt(a[e].r)<parseInt(a[f].r)&&(b=a[e],a[e]=a[f],a[f]=b);return a};d.array_merge=
function(a,b){for(var c=[],e=[],f=0,d=arguments.length;f<d;f++)for(var g in arguments[f])-1==c.indexOf(arguments[f][g].bid)&&(c.push(arguments[f][g].bid),e.push(arguments[f][g]));return e};d.Shuffle=function(a){for(var b,c,e=a.length;e;b=parseInt(Math.random()*e),c=a[--e],a[e]=a[b],a[b]=c);return a};d.toArray=function(a){var b=[];for(x in a)b.push(a[x]);return b};d.escapeHtml=function(a){a=a.replace(/<(span|strong|b)[^>]*>(.*?)<\/(span|strong|b)>/g,"$2");return a=a.replace(/\"/g,"&quot;")};d.dataFav=
function(a){var b={201:[],202:[],203:[]};"undefined"!=typeof a["203"]&&(1==ADS_Game&&(b["203"]=a["203"]),delete a["203"]);"undefined"!=typeof a["201"]&&(1==ADS_Gender&&(b["201"]=a["201"]),delete a["201"]);"undefined"!=typeof a["202"]&&(2==ADS_Gender&&(b["202"]=a["202"]),delete a["202"]);this.arrFav=this.array_merge(b["201"],b["203"],b["202"]);return a};d.getCookie=function(a){return ADS_CHECKER.getStorage(a)};d.setCookie=function(a,b){ADS_CHECKER.setStorage(a,b,0,"/");return!0};d.removeZoneCook=function(a){for(var b=
this.getCookie("cpcSelfServ"),c=a.length-1,e=0;e<c;e++)b=b.replace(a[e]+",","");this.setCookie("cpcSelfServ",b,1,1)};d.addCookie=function(a){var b=this.getCookie("cpcSelfServ");this.setCookie("cpcSelfServ",b+a,1,1)};d.choseBlock=function(a){var b=ADS_CHECKER.getStorage("cpcSelfServ"),c=0,e=Math.floor((new Date).getTime()/1E3);if(-1!=b.indexOf(this.zoneid+"_b_"))var f=b.indexOf(this.zoneid+"_b_"),c=b.indexOf(",",f),f=b.substring(f,c),c=this.explode("_",f),d="",d=4==c.length?parseInt(c[3]):0,c=4==c.length?
parseInt(c[2]):0,c=900<=e-d?Math.floor(Math.random()*a):c,d=900<=e-d?this.zoneid+"_b_"+c+"_"+e:this.zoneid+"_b_"+c+"_"+d,b=b.replace(f,d);else c=Math.floor(Math.random()*a),b+=this.zoneid+"_b_"+c+"_"+e+",";ADS_CHECKER.setStorage("cpcSelfServ",b,0,"/");return c};d.addDefault=function(a,b,c){var e=!1,f="";if(0<b.length&&0<c){3<arguments.length&&(e="string"==typeof arguments[3]?!0:e);var d=Math.min(b.length,c),g=[],k=0;if(e){for(var f=arguments[3],e=0,h=a.length;e<h;e++)g.push(a[e][f]);e=0;for(h=b.length;e<
h&&(ADS_CHECKER.in_array(b[e][f],g)||!(k++,a.push(b[e]),k==d));e++);}else if(b.length<c)a=b;else{b=3<arguments.length?b:this.Shuffle(b);for(e=0;e<d;e++)a.push(b[e])}}return a};d.dupItem=function(a,b){var c=a.length,e=0,f=0,d;d=this.Shuffle(a);len2=d.length;if(0<c&&0<b){e=Math.floor(b/c);f=b%c;if(0<e){for(c=0;c<e;c++)for(var g=0;g<len2;g++)a.push(d[g]);0!=f&&(a=this.dupItem(a,f))}if(0<f&&0==e)for(c=0;c<f;c++)a.push(a[c])}return a};d.OnLoaded=function(a){var b=!1,b="1"==ADS_City||"2"==ADS_City||"3"==
ADS_City||"4"==ADS_City||"5"==ADS_City||"0"==ADS_City||70<parseInt(ADS_City);this.init(a.DATA);a.DATA=this.dataFav(a.DATA);"undefined"!=typeof a.DATA["103"]&&(this.df=this.toArray(a.DATA["103"]),delete a.DATA["103"]);this.zoneid=a.ZONEID;this.resetDefault();var c=this.toArray(a.DATA);a=[];var e=this.rand_limit;if(0<c.length)if(b){var b=this.choseBlock(c.length),b=this.arrayArea(this.toArray(c[b])),c=b.arrCity.length,f=b.arrArea.length;b.arrCity=this.sortRank(b.arrCity);b.arrArea=this.sortRank(b.arrArea);
if((0!=ADS_Game||0!=ADS_Gender)&&0<this.arrFav.length){this.arrFav=this.rankMulti(this.arrFav);f=this.arrayArea(this.arrFav);f.arrCity=this.sortRank(f.arrCity);f.arrArea=this.sortRank(f.arrArea);var d=Math.min(f.arrCity.length,Math.max(4,e));0<f.arrCity.length&&c<=d?(a=this.addDefault(a,f.arrCity,d,!0),a=this.addDefault(a,b.arrCity,c,"bid"),a=this.addDefault(a,b.arrArea,e-a.length,"bid"),a=this.addDefault(a,f.arrArea,e-a.length,"bid")):(d=Math.min(Math.floor(0.7*c),f.arrCity.length),c-=d,a=this.addDefault(a,
f.arrCity,d,!0),a=this.addDefault(a,b.arrCity,c,"bid"))}else a=this.addDefault(a,b.arrCity,c),b.arrCity.length<e&&(a=this.addDefault(a,b.arrArea,e-a.length))}else c=this.arrCity.length,f=this.arrArea.length,8>=c+f?(a=this.addDefault(a,this.arrCity,c),a=this.addDefault(a,this.arrArea,f)):c<e?(a=this.addDefault(a,this.arrCity,c),a=this.addDefault(a,this.arrArea,e-c)):a=this.arrCity;a=this.addDefault(a,this.df,e-a.length);a=this.addDefault(a,arrCPCDf.city,e-a.length);a=this.addDefault(a,arrCPCDf.area,
e-a.length);0<a.length&&e>a.length&&(a=this.dupItem(a,e-a.length));a.length>e&&(a=this.getItem(a));0<this.trkItem.length&&(a[0]=this.trkItem[0]);return a=this.Shuffle(a)};d.getItem=function(a){var b=this.getCookie("cpcSelfServ");this.explode(",",b);var b=b.match(RegExp(this.zoneid+"_([0-9]+)","g")),c=[],e=[],c=a;a=this.rand_limit;if(c.length>a)var c=this.choseData(c,a),f=0;else{if(0<e.length)for(var d=this.choseData(e,a-c.length),f=0,g=d.length;f<g;f++)c.push(d[f]);b&&this.removeZoneCook(b);f=0}for(;f<
a;f++);16<=e.length&&this.removeZoneCook(b);return c};d.choseData=function(a,b){for(var c=[],e=[],d=0,j=a.length;d<j;d++)for(var g=0;g<parseInt(a[d].r);g++)c[c.length]=a[d].bid;c=this.Shuffle(c);for(d=0;d<b;d++){j=Math.floor(Math.random()*c.length);for(g=0;g<a.length;g++)if(a[g].bid==c[j]){e.push(a[g]);break}c=ADS_CHECKER.array_diff(c,[c[j]])}return e};d.explode=function(a,b,c){var d={"0":""};if(2>arguments.length||"undefined"==typeof arguments[0]||"undefined"==typeof arguments[1])return null;if(""===
a||!1===a||null===a)return!1;if("function"==typeof a||"object"==typeof a||"function"==typeof b||"object"==typeof b)return d;!0===a&&(a="1");if(c){var f=b.split(a),d=f.splice(0,c-1),f=f.join(a);("undefined"!=typeof f||""!=f||0<f)&&d.push(f);return d}return b.split(a)};d.test=function(){setTimeout("ssvzone_"+this.zoneid+".test()",1E3)};d.resetDefault=function(){if(arrCPCDf.check)return!1;var a=[],b=[],c=/,[1|2|3],[1|2|3],[1|2|3],/g,d=","+ADS_Location+",",f=","+ADS_City+",",j=[];if(void 0!=typeof _ssv_default&&
"undefined"!=typeof _ssv_default)for(var j=_ssv_default,g=0,k=j.length;g<k;g++){var h=","+j[g].l+",",l=","+j[g].la+",";(c.test(h)||",,"==h||-1!=h.indexOf(d)||-1!=h.indexOf(f)||-1!=l.indexOf(f))&&!ADS_CHECKER.in_array(j[g].bid,__arCPCBL)?a.push(j[g]):-1!=l.indexOf(d)&&!ADS_CHECKER.in_array(j[g].bid,__arCPCBL)&&b.push(j[g])}arrCPCDf.city=a;arrCPCDf.area=b;arrCPCDf.check=!0};d.resetVar=function(){d.trkItem=null;d.arrFav=null;d.df=null;d.arrCity=null;d.arrArea=null;d.zoneid=null;d.template=null;d.css=
null;d.link3rd=null;d.rand_limit=null};r.admCpcZone=l})(window);

function admExecJs(j,d){var f=j,g=[],e=[];this.trim=function(a){a=a.replace(/^\s+/,"");for(var b=a.length-1;0<=b;b--)if(/\S/.test(a.charAt(b))){a=a.substring(0,b+1);break}return a};this.explode=function(){var a=j.match(/<(script)[^>]*>(.*?)<\/(script)>/gi);if(a)for(var b="",c=0,d=a.length;c<d;c++)f=f.replace(a[c],""),b=a[c].replace(/<(script)[^>]*>(.*?)<\/(script)>/gi,"$2"),""!=this.trim(b)&&g.push(this.trim(b)),(b=a[c].match(/src="([^\"]*)\"/gi))&&e.push(b[0].replace(/src="([^\"]*)\"/gi,"$1"))};
this.getFileScript=function(a){var b=document.createElement("script");b.type="text/javascript";b.async=!0;b.src=a;a=document.getElementsByTagName("script")[0];a.parentNode.insertBefore(b,a)};this.explode();if(0<e.length){d=document.getElementById(d);d.innerHTML=f;for(var c=0,h=g.length;c<h;c++)eval(g[c]);c=0;for(h=e.length;c<h;c++)this.getFileScript(e[c])}};

function advfa(b){if("object"==typeof b){if("undefined"!=typeof b.s){var a=b.s,a=a.toString();ADS_CHECKER.setStorage("s",a,"","/")}"undefined"!=typeof b.g&&(a=b.g,a=a.toString(),ADS_CHECKER.setStorage("g",a,"","/"))}};



(function(){
	if('localStorage' in window && window['localStorage'] !== null){
		var ver=ADS_CHECKER.getStorage("ver");
		if(ver=='' || ver.replace(/timestamp_([0-9]+)\,/g,'')!='19'){
			localStorage.clear();
			ADS_CHECKER.setStorage('ver', '19', '', '/');
		}
	}
	var _urlDomain=document.domain;
	
	_admloadJs("http://logging.admicro.vn/_cpm4k.js");
	_admloadJs('http://logging.admicro.vn/ps');
	_admloadJs('http://logging.admicro.vn/cpcbl');
	
	
	if(_urlDomain.indexOf('dantri.com.vn')!=-1){
		var img =new Image();
		img.src='http://logging.admicro.vn/_adv.gif?adm_domain='+encodeURIComponent(document.URL)+'&adm_campaign=1000310&adm_aditem=54016&adm_zoneid=1&adm_channelid=-1&random='+Math.random();
	}
	
		_admloadJs("http://logging.vietid.net/tracking_active_user.php");
	
})();
